### ISSUE TITLE
Would eggnog-mapper support viral OG?

### ISSUE THREAD

**Issue by ecastron** [jhcepas/eggnog-mapper#1]
Dear @jhcepas,

Thanks for putting together this tool. Quick question: the new version of EggNOG includes virus OG. Would eggnog-mapper support viral OG?

Cheers,

@ecastron

**Comment by jhcepas** [comment]
thanks @ecastron, 
it does not include viruses at the moment, but it should be trivial to add it. I will hmmpress all viral HMM and add it to the tool.

**Comment by ecastron** [comment]
Excelente, gracias!

@ecastron

**Comment by seguajardo** [comment]
Dear @jhcepas,
It is a really nice tool, but I have the same issue. Did you have time to add the viral HMM to the tool?
Would be nice to have it.

Thanks.
Sergio.
