### ISSUE TITLE
questions about the KO information

### ISSUE THREAD

**Issue by quliping** [jhcepas/eggnog-mapper#100]
In my result, some protein sequences got more than one KO number. Like this:
![image](https://user-images.githubusercontent.com/39583607/44581651-2674ea80-a7d1-11e8-839e-639363ae3a91.png)
Then which KO number should I use? They mean different parts of the KEGG pathway ...

**Comment by jhcepas** [comment]
in principle, all of them. It could be a multidomain protein for instance...

**Comment by lijingdi** [comment]
Hi quliping, have you solved this problem? I ran into the same problem

**Comment by Cantalapiedra** [comment]
Hi,

BlastKOALA seems to perform homology search against groups of orthologous which have been specifically assigned a single identifier (the K). From https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3965122/

"The BlastKOALA and GhostKOALA servers utilize the BLASTP [11] and GHOSTX [12] programs, respectively, for searching the non-redundant GENES database."
"BlastKOALA, the K number assignment is performed using the weighted sum of BLAST bit scores, where the weighting scheme is the same as the internally used KOALA algorithm excluding the bidirectional best-hit information."

However, eggnog includes a different set of orthologous groups, which do not relate 1-1 with KOs.

Therefore, as in almost every comparison between bioinformatics tools, results are different.
In my opinion, the question is not "which result should I trust?", but, "how do I interpret the results from the different tools?". 
As those tools are different, and rely on different databases and algorithms, the interpretation should be different too.

Somehow, it is surprising to me that you always get a single K for every query in BlastKOALA. I would expect that for some queries there would be more than one hit to the KEGG database with similar weighted scores.

I hope that makes sense.

Best,
Carlos

**Comment by XMTian** [comment]
Hi,

I have a question about how to do functional enrichment. Since different genes might be annotated to the same K number, when we use these K number to do enrichment, should we get a unique K number set or not? Will this influence the functional enrichment result?

Thanks in advance!

**Comment by Cantalapiedra** [comment]
Hi,

I hope that someone with more knowledge about enrichment analysis could answer your question.
I would guess that you want to count, for each K, in how many genes is annotated, and compare 2 sets of genes. But this is just guessing...
