### ISSUE TITLE
incompatible diamond database

### ISSUE THREAD

**Issue by echopan0731** [jhcepas/eggnog-mapper#104]
Hi
I try the example command for using diamond based search but it tells me that it requires a different version of diamond. Do you know how can I update my diamond database?
Thanks!

python emapper.py -i test/p53.fa --output p53_maNOG  -m diamond
#  emapper-1.0.3-3-g3e22728
# ./emapper.py  -i test/p53.fa --output p53_maNOG -m diamond
  /usr/local/bin/diamond blastp -d /home/fstrklab/eggnog-mapper/data/eggnog_proteins.dmnd -q /home/fstrklab/eggnog-mapper/test/p53.fa --more-sensitive --threads 2 -e 0.001000 -o /home/fstrklab/eggnog-mapper/emappertmp_dmdn_wbd3mu/ba9e3cad014341bb9660849b52932229 --top 3
**Error: Database was built with a different version of diamond as is incompatible**.
Traceback (most recent call last):
  File "emapper.py", line 1009, in <module>
    main(args)
  File "emapper.py", line 220, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "emapper.py", line 361, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/usr/local/bin/diamond blastp -d /home/fstrklab/eggnog-mapper/data/eggnog_proteins.dmnd -q /home/fstrklab/eggnog-mapper/test/p53.fa --more-sensitive --threads 2 -e 0.001000 -o /home/fstrklab/eggnog-mapper/emappertmp_dmdn_wbd3mu/ba9e3cad014341bb9660849b52932229 --top 3' returned non-zero exit status 1

**Comment by jhcepas** [comment]
you probably need to use the diamond version distribute with the code, which is the one used to create the database. 
We will upgrade diamond (and dbs) in the next version
