### ISSUE TITLE
not a gzipped file

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#11]
Hi @jhcepas, the new version give an error with a gzipped file, what can I do?
the code are:
> emapper.py -i testCOG0515.fa -o test -d bact --cpu 16 --override
> Sequence mapping starts now!
>  Processed queries:5 total_time:21.0365080833 rate:0.24 q/s
> Hit refinement starts now
> Traceback (most recent call last):
>   File "/home/ecastron/programs/eggnog-mapper/emapper.py", line 684, in <module>
>     main(args)
>   File "/home/ecastron/programs/eggnog-mapper/emapper.py", line 198, in main
>     refine_matches(refine_file, hits_file, args)
>   File "/home/ecastron/programs/eggnog-mapper/emapper.py", line 355, in refine_matches
>     for line in gopen(OGLEVELS_FILE)])
>   File "/home/ecastron/programs/python/lib/python2.7/gzip.py", line 446, in readline
>     c = self.read(readsize)
>   File "/home/ecastron/programs/python/lib/python2.7/gzip.py", line 252, in read
>     self._read(readsize)
>   File "/home/ecastron/programs/python/lib/python2.7/gzip.py", line 287, in _read
>     self._read_gzip_header()
>   File "/home/ecastron/programs/python/lib/python2.7/gzip.py", line 181, in _read_gzip_header
>     raise IOError, 'Not a gzipped file'
> IOError: Not a gzipped file
> 

cheers

**Comment by jhcepas** [comment]
@Sanrrone is the file "og2level.tsv.gz" present in data/ ?
It should be part of the latest release.

**Comment by Sanrrone** [comment]
the file was in the folder but not updated, now everything works, thanks!
