### ISSUE TITLE
download_eggnog_data.py scripts couldn't run

### ISSUE THREAD

**Issue by wenjingcui** [jhcepas/eggnog-mapper#113]
DEAR professor,
when i running this code "download_eggnog_data.py bact" under python2.7 and 3.5,but it all gives errors like bellow:
_###   File "/root/eggnog-mapper/download_eggnog_data.py", line 10
    print colorify(cmd, 'cyan')
                 ^
SyntaxError: invalid syntax_
could you tell me how can i solve this problem? i am a freshman in bionformatics, any help and advises are very appreciated!
BEST REGARDS,
WENJING CUI

**Comment by jhcepas** [comment]
it looks like you are trying to use it with python 3 (currently unsupported)
