### ISSUE TITLE
add all DB options

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#16]
I'm working with a metagenome sample and will be nice use this option.
now only is possible ran -db bact|euk|arch separately

regards

**Comment by jhcepas** [comment]
you can specify individual eggNOG divisions (i.e. maNOG, priNOG, etc...).  `-db NOG`, which points to the root level containing all species should do the trick. However, this database is not optimized (i.e. large groups are not divided intro smaller HMM models). Next release will offer an alternative mode based on DIAMOND searches: running faster, searching against all proteomes in one shot, and so far producing similar results in our benchmarks.

**Comment by jhcepas** [comment]
diamond mode already available. This uses the whole database as target
