### ISSUE TITLE
Error running diamond

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#19]
after loading git module:

> ~/programs/eggnog-mapper-0.11.0/emapper.py -i testCOG0515.fa -o output_bact -d bact --cpu 16 -m diamond
> #  
> \# ./emapper.py  -i testCOG0515.fa -o output_bact -d bact --cpu 16 -m diamond --override
>   /home/ecastron/programs/eggnog-mapper-0.11.0/bin/diamond blastp -d /home/ecastron/programs/eggnog-mapper-0.11.0/data/eggnog_proteins.dmnd -q /home/ecastron/programs/eggnog-mapper-0.11.0/test/testCOG0515.fa --more-sensitive --threads 16 -e 0.001000 -o /home/ecastron/programs/eggnog-mapper-0.11.0/emappertmp_dmdn_v3OGhI/13983698aeb04e8d843512cdad7e2d9f --top 3
> /home/ecastron/programs/eggnog-mapper-0.11.0/bin/diamond blastp -d /home/ecastron/programs/eggnog-mapper-0.11.0/data/eggnog_proteins.dmnd -q /home/ecastron/programs/eggnog-mapper-0.11.0/test/testCOG0515.fa --more-sensitive --threads 16 -e 0.001000 -o /home/ecastron/programs/eggnog-mapper-0.11.0/emappertmp_dmdn_v3OGhI/13983698aeb04e8d843512cdad7e2d9f --top 3
> Traceback (most recent call last):
>   File "/home/ecastron/programs/eggnog-mapper-0.11.0/emapper.py", line 895, in <module>
>     main(args)
>   File "/home/ecastron/programs/eggnog-mapper-0.11.0/emapper.py", line 214, in main
>     dump_diamond_matches(args.input, seed_orthologs_file, args)
>   File "/home/ecastron/programs/eggnog-mapper-0.11.0/emapper.py", line 331, in dump_diamond_matches
>     raise ValueError('Error running diamond')
> ValueError: Error running diamond
> 

regards

**Comment by jhcepas** [comment]
It works for me... could it be a memory problem? DIAMOND required close to 7 o 8 GB with this example. Also, make sure you are using the last version.  
```
$ ./emapper.py -i test/testCOG0515.fa -o output_bact -d bact --cpu 16 -m diamond
#  0.12.2
# ./emapper.py  -i test/testCOG0515.fa -o output_bact -d bact --cpu 16 -m diamond
  /alpha/local/huerta/eggnog-mapper-0.12.3/bin/diamond blastp -d /alpha/local/huerta/eggnog-mapper-0.12.3/data/eggnog_proteins.dmnd -q /alpha/local/huerta/eggnog-mapper-0.12.3/test/testCOG0515.fa --more-sensitive --threads 16 -e 0.001000 -o /alpha/local/huerta/eggnog-mapper-0.12.3/emappertmp_dmdn_XCK6mV/9f563cb600ca444ead795cbcf544b5ae --top 3

Functional annotation of refined hits starts now
 Processed queries:6 total_time:0.0357160568237 rate:167.99 q/s
Done
   output_bact.emapper.seed_orthologs
   output_bact.emapper.annotations
Total time: 1604.42 secs
```

**Comment by Sanrrone** [comment]
you are right, was the memory the problem, running in a cluster works fine.
Thanks

**Comment by jhcepas** [comment]
great. thanks for reporting all those issues.
