### ISSUE TITLE
arguments commented out of annotate.py

### ISSUE THREAD

**Issue by vnkoparde** [jhcepas/eggnog-mapper#2]
#parser.add_argument('--go', dest='go', action='store_true')    
    #parser.add_argument('--kegg', dest='kegg', action='store_true')
    #parser.add_argument('--desc', dest='desc', action='store_true')
    #parser.add_argument('--smart', dest='smart', action='store_true')
These arguments do not work any more from annotate.py.
I was trying to do the test case as per you instructions 
"python annotate.py testCOG0515.hits.tsv --go --kegg --smart --desc > testCOG0515.annotations.tsv"
But it fails.

**Comment by jhcepas** [comment]
@vnkoparde, true, all annotations are now performed by default, no need to specify them as flag arguments. 
 
I will fix documentation, thanks for reporting.

**Comment by vnkoparde** [comment]
Thanks.
Is there a way, I can also get the single letter eggNOG categories in out
annotated output?


Vishal N Koparde, Ph. D.
NGS Bioinformatics Scientist,
Nucleic Acid Research Facilities/
Center for Study of Biological Complexity,
1101 East Marshall Street, #5-050,
P.O. Box 980678
Virginia Commonwealth University
Richmond VA 23298-0678
Email: vnkoparde@vcu.edu
Phone: +1-804-628-3060

**Comment by jhcepas** [comment]
this is reported in the "COG_categories" file

**Comment by vnkoparde** [comment]
Also, full_report is giving an error with annotate.py

>  python annotate.py  --output testCOG0515.annotations.tsv
testCOG0515.hits.tsv
Loading OG meta data for 29 OGs...
Annotating 5 queries...
Done!

>  python annotate.py --full_report --output testCOG0515.annotations.tsv
testCOG0515.hits.tsv
Loading OG meta data for 29 OGs...
Annotating 5 queries...
Traceback (most recent call last):
  File "annotate.py", line 171, in <module>
    main(args)
  File "annotate.py", line 145, in main
    tabprint(OUT[k[1]], " "*len(qname), *(hit_details[i]+list(k)))
KeyError: u'Pkinase'




Vishal N Koparde, Ph. D.
NGS Bioinformatics Scientist,
Nucleic Acid Research Facilities/
Center for Study of Biological Complexity,
1101 East Marshall Street, #5-050,
P.O. Box 980678
Virginia Commonwealth University
Richmond VA 23298-0678
Email: vnkoparde@vcu.edu
Phone: +1-804-628-3060

**Comment by Sanrrone** [comment]
I got the same error, 

> testCOG0515.hits.tsv
> Loading OG meta data for 29 OGs...
> Annotating 5 queries...
> Traceback (most recent call last):
>   File "annotate.py", line 171, in <module>
>     main(args)
>   File "annotate.py", line 145, in main
>     tabprint(OUT[k[1]], " "*len(qname), *(hit_details[i]+list(k)))
> KeyError: u'Pkinase'

is --full_report necessary ? or by default is performed?

**Comment by jhcepas** [comment]
thanks for reporting. I am working on this at the moment. Hope to have some fixes soon.
