### ISSUE TITLE
annotate_hits_file function IndexError

### ISSUE THREAD

**Issue by AlgJWZ** [jhcepas/eggnog-mapper#23]
Hi,
This option will be nice for my transcriptome annotation. When I run the example, it crashed with an error.
`python emapper.py -i test/p53.fa -d euk -o p53`

`#  emapper-0.12.6`
`# ./emapper.py  -i test/p53.fa -d euk -o p53`
`Sequence mapping starts now!`
` Processed queries:1 total_time:31.3815100193 rate:0.03 q/s`
`Hit refinement starts now`
` Processed queries:1 total_time:11.6989130974 rate:0.09 q/s`
`Reading HMM matches`
`Functional annotation of refined hits starts now`
`Traceback (most recent call last):`
`  File "./emapper.py", line 897, in <module>`
`    main(args)`
`  File "./emapper.py", line 259, in main`
`    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)`
`  File "./emapper.py", line 625, in annotate_hits_file`
`    match_levels = set([nog.split("@")[1] for nog in match_nogs])`
`IndexError: list index out of range`

p53.emapper.seed_orthologs:
`#query_name     best_hit_eggNOG_ortholog        best_hit_evalue best_hit_score`
`9606.p53        9598.ENSPTRP00000014836 2.5e-277        910.6`

p53.emapper.hmm_hits:
`# #query_name   hit     evalue  sum_score       query_length    hmmfrom hmmto   seqfrom seqto   query_coverage`
`9606.p53        euNOG.ENOG410IITK.meta_raw      7.7e-217        723.3   392     1       373     1       392     0.997448979592`

python version: Python 2.7.12

Hope for your help.
Regards.

**Comment by AlgJWZ** [comment]
Hi,
I have fix this error by using the Python 2.7.5 version.

**Comment by jhcepas** [comment]
@AlgJWZ yes, python 2.7 is required. thanks
