### ISSUE TITLE
Setting up large analyses link broken

### ISSUE THREAD

**Issue by courtneystairs** [jhcepas/eggnog-mapper#24]
Hi Jamie, 

I noticed on the wiki that the setting up large analyses link is broken - or maybe its just under construction.  Are there plans to add this page, I would be very interested! :) 

C

**Comment by jhcepas** [comment]
yes, coming soon :)
I was planning to provide a couple of tweaks that I found useful when
computing annotation of really large datasets in a cluster and using shared
filesystems.
Feel free to ask if you are encountering specific problems.

**Comment by boulund** [comment]
Hi, 

I'm really interested in how the best apply eggnog-mapper to large datasets in cluster environments with shared filesystems. Do you have a draft of the unfinished wiki-page I could have a look at (or maybe contribute to)?

**Comment by jhcepas** [comment]
I added a few tricks, based on the changes made in latest versions. hope it helps
