### ISSUE TITLE
Emapper online - NOG name instead of top hit? KO instead of map?

### ISSUE THREAD

**Issue by courtneystairs** [jhcepas/eggnog-mapper#25]
Hi Jamie, 

I was wondering if there is a mapping file of eggNOG where I could relate the top hit back to the actual NOG name + number (rather than the accession number for that particular protein).  

Furthermore, is there a mapping file to go from the eggNOG number to the KEGG orthology rather than the map number?

Are these options implemented in the stand-alone version?

Thank you very much for your help :)
Courtney

**Comment by jhcepas** [comment]
Hi Courtney,
The "members.tsv" files in the download section (
http://eggnogdb.embl.de/#/app/downloads) provides content information of
each eggNOG group (both number of members, species and actual list of
accessions). If the taxonomic scope of your searches are not restricted,
you may need to download the member files for all taxonomic levels.

Regarding KEGG KOs, no, this is not available yet, but we are woking on
expanding the functional database sources and KOs will be included in next
releases.

**Comment by rohansachdeva** [comment]
I think this file "eggnog4.protein_id_conversion.tsv.gz" from the FTP provides mappings to KEGG IDs. You could then use the KEGG API To get the KOs for each ID. 

@jhcepas does that sound right?

**Comment by jhcepas** [comment]
That's right, but it is an old conversion and not sure how much work would
require using the KEGG API.
KO mappings are close to be ready in the main branch so, if possible, I
would suggest to wait until they are officially integrated.

**Comment by jhcepas** [comment]
KO modules feature request issue: #43

**Comment by rohansachdeva** [comment]
Are the mappings in "eggnog4.protein_id_conversion.tsv.gz"  to RefSeq up to date? Because they could be used to pull KOs from the KEGG API.

**Comment by jhcepas** [comment]
not really, refseq ids are two or three years old at least.
