### ISSUE TITLE
Cannot run search with HMMER against "bact"  (nor "--usemem")

### ISSUE THREAD

**Issue by xmarti6** [jhcepas/eggnog-mapper#26]
Hi, 
This tool seem really useful, but I'm having issues testing your tool with "bact" database.
I tried running:

Nevertheless I thing it has to do with a bug in:
if **not** args.mode == 'diamond' and not pexists(EGGNOG_DMND_DB):

I believe "not" should be removed. Could you confirm this?

[fail]python emapper.py -i ../file.fa --output ../file.fa.bact --cpu 5 -d bact
DIAMOND database data/eggnog_proteins.dmnd not present. Use download_eggnog_database.py to fetch it
[fail]python emapper.py -i ../file.fa --output ../file.fa.bact --cpu 5 -d ./data/hmmdb_levels/bact_50/bact_50.hmm
DIAMOND database data/eggnog_proteins.dmnd not present. Use download_eggnog_database.py to fetch it

[succeded after removing "not"]
python emapper.py -i ../file.fa --output ../file.fa.bact --cpu 5  -d ./data/hmmdb_levels/bact_50/bact_50.hmm 

-Furthermore, if I use "--usemem" option it gets stucked repeating the "Waiting..." line:
[fail] python emapper.py  -i -i ../file.fa --output ../file.fa.bact --cpu 5 --usemem -d ./data/hmmdb_levels/bact_50/bact_50.hmm
\#  emapper-unknown
\# ./emapper.py  -i -i ../file.fa --output ../file.fa.bact --cpu 5 --usemem -d ./data/hmmdb_levels/bact_50/bact_50.hmm
Loading server at localhost, port 53000-53001
Waiting for server to become ready... localhost 53000
Waiting for server to become ready... localhost 53000
...
Don't know if in this case might be something I had configure in my computer.

Many thanks
Xavi

**Comment by jhcepas** [comment]
@xmarti6 thanks. The diamond check was indeed incorrect. I have solved this in version 0.12.7. 

The "Waiting" message when using --usemem is entirely normal, especially for large DBs such as bact. It has to load ~40GB of data into memory and this usually takes from seconds to minutes. You can monitor with `top` if the process is actually loading data into memory. If does is not the case, please open a new issue. 

thanks again for reporting the problem.
