### ISSUE TITLE
Could not run emapper

### ISSUE THREAD

**Issue by chelseaju** [jhcepas/eggnog-mapper#27]
I download eggnog-mapper from github, and download the bacteria database with the following command line
> python download_eggnog_data.py bact

I then run emapper using the test data:
> python emapper.py -i test/polb.fa --output polb_back -d bact

It gives me the following error message:
Error: bad file format in HMM file data/hmmdb_levels/bact_50/bact_50.hmm

When i list out the files under data/hmmdb_levels/bact_50, it contains
"bact_50.hmm.h3f"  "bact_50.hmm.h3i"  "bact_50.hmm.h3m"  "bact_50.hmm.h3p" "bact_50.hmm.idmap"  "bact_50.info"  "bact_50.pkl"

Does anyone know if it is a bug in emapper? Or if I didn't download the data correctly?! Any help is appreciated. Thanks!!

**Comment by jhcepas** [comment]
@chelseaju , most probably one of the files didn't download correctly. 
Can you check the md5sum of all those files? These is how they should look:
```
$ md5sum *
dec0a42cccd7980df7cf1deba4c67aae  bact_50.hmm.h3f
ff8aa06c3d3feb21eafbb60fdf4545d7  bact_50.hmm.h3i
8b98e662769ba703a54daa30e05f3b79  bact_50.hmm.h3m
13965f23c4e7c746640adc5b829741b6  bact_50.hmm.h3p
83790065e3171e23e9cd3f9a4e48d599  bact_50.hmm.idmap
a26db28c16818c472d787de5c63d5460  bact_50.info
aa1e995a371b1cb17cc6e8f1d06fdb5c  bact_50.pkl 
```

**Comment by chelseaju** [comment]
Thanks so much for the quick response! Yeah, one of the file was corrupted during the download. Re-running the download script fixes that problem. However, I am experiencing a new error message, which says 
> IOError: [Errno 2] No such file or directory: 'EggNOG_mapper/eggnog-mapper/data/og2level.tsv.gz' 

I check the repository, and do not see any file named "og2level.tsv.gz". How can we get this file?

**Comment by jhcepas** [comment]
Are you using the latest release? 
that file is part of this repository:  https://github.com/jhcepas/eggnog-mapper/tree/master/data

**Comment by chelseaju** [comment]
Thanks so much for pointing that out. It works now 💃 👍
