### ISSUE TITLE
Inconsistent qlen when parsing hmmscan output

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#29]
Hi jhcepas, I have a proteins of coli (and some pseudo genes), and im using the 0.12.6 version of this mapper but no output is write, can you help me?.

> ./emapper.py  -i selected.faa -o output_bact -d bact --cpu 16
> 
> Traceback (most recent call last):
>   File "/home/ecastron/programs/eggnog-mapper-0.12.6/emapper.py", line 897, in <module>
>     main(args)
>   File "/home/ecastron/programs/eggnog-mapper-0.12.6/emapper.py", line 220, in main
>     dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
>   File "/home/ecastron/programs/eggnog-mapper-0.12.6/emapper.py", line 376, in dump_hmm_matches
>     cpus=args.cpu)):
>   File "/home/ecastron/programs/eggnog-mapper-0.12.6/eggnogmapper/search.py", line 282, in hmmscan
>     "Inconsistent qlen when parsing hmmscan output")
> ValueError: Inconsistent qlen when parsing hmmscan output
> 

regards
[selected.faa.zip](https://github.com/jhcepas/eggnog-mapper/files/685783/selected.faa.zip)

**Comment by jhcepas** [comment]
Hi @Sanrrone , I just tried your data and seems to run ok with the following command: 
`python eggnog-mapper/emapper.py -i /tmp/selected.faa -o /tmp/output_bact -d bact:localhost:51500 --cpu 16`

Please reopen if the problem persists.
