### ISSUE TITLE
UnboundLocalError: local variable 'annot_levels' referenced before assignment

### ISSUE THREAD

**Issue by webermarcolivier** [jhcepas/eggnog-mapper#30]
```
  File "[...]/eggnog-mapper-0.12.7/emapper.py", line 638, in annotate_hits_file
    all_orthologies = annota.get_member_orthologs(best_hit_name, target_levels=annot_levels)
UnboundLocalError: local variable 'annot_levels' referenced before assignment
```

When `tax_scope` option is set to auto (default) and the best hit NOG gives `match_levels` equal to the general taxonomic level `['NOG']`, the latter is not found in the list `TAXONOMIC_RESOLUTION` and result in an undefined `annot_levels`.

**Comment by jhcepas** [comment]
thanks @webermarcolivier 
this was solved in the `bigg` branch, but I just to include the fix in `master.
