### ISSUE TITLE
Statistics of annotation file off by 1

### ISSUE THREAD

**Issue by ealdraed** [jhcepas/eggnog-mapper#31]
Hello and kudos to @jhcepas for your work.

After running eggnog-mapper I noticed that the statistics reported at the end of the `*.annotations` file are +1 compared to what is read in the `*.seed_orthologs` file.

Based on the loop and the increment used in the `annotate_hits_file` function, I guess the variable `qn` should be reported instead of `qn + 1` or `qn+1` in the following lines:

https://github.com/jhcepas/eggnog-mapper/blob/c436da5779b333531038eacfaa0a0d4255696544/emapper.py#L717-L727

I suppose the `annotate_hits_file_sequential` function (which is not used at the moment, isn't it?) has the same issue (https://github.com/jhcepas/eggnog-mapper/blob/c436da5779b333531038eacfaa0a0d4255696544/emapper.py#L842-L848) as well as `annotate_hmm_matches` (https://github.com/jhcepas/eggnog-mapper/blob/c436da5779b333531038eacfaa0a0d4255696544/emapper.py#L461-L467).

**Comment by jhcepas** [comment]
good catch. It should be corrected in the current master branch
