### ISSUE TITLE
Version info "unknown" and not printed consistently in output files

### ISSUE THREAD

**Issue by ealdraed** [jhcepas/eggnog-mapper#32]
Hello,

I noticed the version info is printed as `unknown` when using release 0.12.7 or a git cloned version with removed `.git` folder.

It seems related to a non-functioning import from `eggnogmapper/common.py`. Removing/commenting line 1 (`from __future__ import absolute_import`) or modifying line 15 to `from .version import __VERSION__` or `from eggnogmapper.version import __VERSION__` fixes the problem.

Furthermore, the header data at the start of the output files differs for the `*.annotations` file in that it is missing the emapper version and an empty comment line before the comment header.

To fix this, I suppose `annotate_hits_file` (and `annotate_hits_file_sequential`) should use the `get_call_info` function.

Regards

**Comment by ealdraed** [comment]
I can't really estimate what it would mean to delete line 1, so from what I gathered it is the way to go with absolute paths. So I guess to fix the issue, go with implementing the relative import on `common.py` -> `from .version import __VERSION__`.

What do you think?

Do you want me to file a pull request to possibly make things easier?

I think the header part is an easy fix and I should've separated it from this issue...

**Comment by jhcepas** [comment]
Thanks @ealdraed !, should be fixed in the master branch now.
