### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by mcharlene** [jhcepas/eggnog-mapper#34]
Since yesterday afternoon I get the message "Error loading data" when trying to upload fasta files. Are there any issues with the eggnog-mapper at the moment?

**Comment by jhcepas** [comment]
Yes, but they should be solved now.

**Comment by MaryoHg** [comment]
Hi, both @mcharlene, @jhcepas.

I'm having this issue at the moment.
May you help giving me some advice?

I've already upload a fasta file weeks earlier but I'm unable to do it now.


Thanks in advance,


Maryo.
