### ISSUE TITLE
error when running emapper

### ISSUE THREAD

**Issue by igsbma** [jhcepas/eggnog-mapper#36]
Hi there, when I was trying on a test file

$ cat test.fa 
>2512392153
MVLMTVALSLAAKTIAVAVIASQVAQAIAQLTAAKTSCNY

but got this error, could you advice? 

$ ./runEggnog.sh test.fa 
#  emapper-0.12.6
# ./emapper.py  -i test.fa --output test -d bact
Sequence mapping starts now!
Traceback (most recent call last):
  File "path/eggnog-mapper/emapper.py", line 897, in <module>
    main(args)
  File "path/db/eggnog-mapper/emapper.py", line 220, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "path/db/eggnog-mapper/emapper.py", line 383, in dump_hmm_matches
    print >>OUT, '\t'.join([name] + ['-'] * (len(hits_header) - 1))
TypeError: sequence item 0: expected string, float found

It seems running fine for other sequences, such as the following:
>seqs
MSSTPVFDLQPLGVKPFESEREFWDSSSTLKSLYKYAQACSASPHAVLVCSLARVCALVPSTIVIPPFIGGSPATLNFAAITIGEPGGGKGLAMSVAKELIQFPDTVWTGQTASGEAIPRAYVHYEVEDNTGKADDGEGEKRERNRTRLKYSKANAFFDIPEVREFAANTSRVGSTLVPVLVKLIDGTTKLGCTTKCESNTLQVPEYGYRAAIVVGVQPANIRDITSHDGTGLPQRFLWTDVFDLDAPEVADLPERTAPSEWLPFKADAFNQYACSMRDLNSLLENGNELHRYELNYPKGVPESVKQNARKKLRREDDAKHGHSQLLVLKTAAIIALFLQEDKSNLLNVTAKNIQQAEWLVRQSLETVKNGLDEYTQTKNAETYRQEYDTKGDEEKEPLIQNVERSIIRKLEKSNGQGISNRDINRMLNVEKRPAISDALAALIKSKTIQEKDGKYYLTK
>seq2
MKKPPFNTVSHEGGWDNSSNYTPLPCDYNFAKMSTEQQLDCFADGFARAIYEPFNLAVGSDVERRCRMFALAALSSVTEGCEKHKISAKGSDVDALAGIIILAMACPNAVVTIDFSGKIQNGVIRLNTPEHLSRFGEIECLPMSRAWFLENNPRVHAAKIREHLLEVAPLHKESSLTEMLEECDKDCWRNLMKPPSMEVTK

Thank you very much!

**Comment by jhcepas** [comment]
@igsbma It seems that you are not using a a correct FASTA format. Please try with something like: 
```
>2512392153
MVLMTVALSLAAKTIAVAVIASQVAQAIAQLTAAKTSCNY
```

reopen this issue if that's not the problem. 
tx
