### ISSUE TITLE
Mammalian specific example - database not found

### ISSUE THREAD

**Issue by rohansachdeva** [jhcepas/eggnog-mapper#37]
Hi, 
I am trying to to run from the documentation:

`python emapper.py -i test/p53.fa --output p53_maNOG -d maNOG`

And get this output:

[False, False, False, False, False]
Database maNOG not present. Use download_eggnog_database.py to fetch it
Traceback (most recent call last):
  File "emapper.py", line 1082, in <module>
    main(args)
  File "emapper.py", line 218, in main
    host, port, dbpath, scantype, idmap = setup_hmm_search(args)
  File "emapper.py", line 64, in setup_hmm_search
    raise ValueError('Database not found')
ValueError: Database not found

**Comment by jhcepas** [comment]
@rohansachdeva you have to download the `maNOG` database first:

` python download_eggnog_database.py maNOG`
