### ISSUE TITLE
Speed of annotation - hmmer vs. diamond

### ISSUE THREAD

**Issue by dplichta** [jhcepas/eggnog-mapper#38]
I am comparing hmm and diamond mode in emapper-0.12.7 on our local cluster and, contrary to what I expected, I found that hmm was faster than diamond. The former mode took ~2.5h, the latter ~6.5h. Could you advice on the settings?

The test setup contains 10k microbial genes (eventually I want to annotate >1M sequences). The following commands were submitted to a node with 28 cores and 120 gb memory:

emapper.py -m hmmer -i 1k.fa --translate --output eggnog.hmmer.1k -d bact --usemem --cpu 28

emapper.py -m diamond -i 1k.fa --translate --output eggnog.diamond.nr.1k --usemem --cpu 28 --scratch_dir /scratch/$PBS_JOBID/ --temp_dir /scratch/$PBS_JOBID/

Note:
1. /scratch/$PBS_JOBID/ - designated physical space for temporary files on the node
2. There is also /tmp/$PBS_JOBID/ - designated memory space for temporary files on the node, but when I tried using that for --temp_dir and --scratch_dir it returned 'ValueError: Error running diamond'.

Thanks for help!

**Comment by jhcepas** [comment]
DIAMOND speed largely depends on the original size of the input data (more sequences=larger speedups). HMMER mode performance is linear, so you could expect ~200h for 1M sequences wiht the same setup. DIAMOND will definitely not take that long.  
I would have said that with 10k genes one can already see some improvement using diamond, though

**Comment by dplichta** [comment]
Alright, thanks for a quick reply.

One more thing. Regarding the memory footprint, should I expect a heavier memory load on a query with more sequences or is it database-size dependent only?

Damian

**Comment by jhcepas** [comment]
in hmmer mode, memory is mostly database-dependant (input sequences are processed sequentially). Diamond runs depend on both input-size and database-size.
