### ISSUE TITLE
Error running basic example

### ISSUE THREAD

**Issue by rohansachdeva** [jhcepas/eggnog-mapper#39]
I am trying to run:
`python emapper.py -i test/polb.fa --output polb_bact -d bact`

after having downloaded using: 
`python download_eggnog_data.py -y euk bact arch viruses maNOG`

This is what data/hmmdb_levels looks like:
`arch_1  bact_50  euk_500  maNOG_hmm  viruses_hmm`

I get the following error:
`[False, False, False, False, False]
Database bact not present. Use download_eggnog_database.py to fetch it
Traceback (most recent call last):
  File "emapper.py", line 1082, in <module>
    main(args)
  File "emapper.py", line 218, in main
    host, port, dbpath, scantype, idmap = setup_hmm_search(args)
  File "emapper.py", line 64, in setup_hmm_search
    raise ValueError('Database not found')
ValueError: Database not found`

Thanks!

**Comment by jhcepas** [comment]
are you on the latest version? I just tried on my computer and everything runs. 
Can you ls -R the data dir?

**Comment by rohansachdeva** [comment]
I'm on 0.99 which I believe is the latest. 

Here's the output of "ls -R" on data: https://www.dropbox.com/s/qwq3esw201qhk5f/lsr.txt?dl=0

**Comment by jhcepas** [comment]
you db folders are empty. Try to delete OG_fasta and all hmmdb dirs and download again.
Not sure if you can trust the other files you downloaded. Might be worth start over on a clean installation

**Comment by rohansachdeva** [comment]
I gave that a shot but will try again.

**Comment by jhcepas** [comment]
ok, check if the download script finishes ok or reports any problem..

**Comment by rohansachdeva** [comment]
Same issue. I didn't notice any issues while downloading. 

Here's the stdout/stderr: https://www.dropbox.com/s/v60f9t1w91box8e/download.log?dl=0

**Comment by jhcepas** [comment]
Ok, I found the problem: The downloading links were pointing to eggNOG-beta, and those URLs were changed recently. I just updated the download script, re-running  `python download_eggnog_data.py -y euk bact arch viruses maNOG` should now download the correct files.

**Comment by rohansachdeva** [comment]
Looks like that fixed it - thanks so much!
