### ISSUE TITLE
emapper.py skips query sequence in output

### ISSUE THREAD

**Issue by carlosj-rr** [jhcepas/eggnog-mapper#396]
Hello, I'm running a set of 10 sequences through emapper.py, to get the orthogroups to which each belong, but my *emapper.annotations output shows results for 9 of them only. These are all metazoans.

Here's my query:
[OG_1051_allspp.fas.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053872/OG_1051_allspp.fas.txt)
And here are the result files (notice that the *annotations and *seed_orthologs both say that '9 queries were scanned', when the query file contains 10 sequences):
[OG_1051_test.emapper.hits.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053890/OG_1051_test.emapper.hits.txt)
[OG_1051_test.emapper.seed_orthologs.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053891/OG_1051_test.emapper.seed_orthologs.txt)
[OG_1051_test.emapper.annotations.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053892/OG_1051_test.emapper.annotations.txt)

In order to see whether I was missing some error message, I extracted only the sequence that was being ignored, and used that as a single-sequence query (this is a flatworm sequence, and the other flatworm in the dataset is processed normally):
[Schmed_test.fas.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053898/Schmed_test.fas.txt)

The command line I'm using is:
```emapper.py --cpu 8 -o Schmed_test -m diamond --dmnd_algo ctg -i Schmed_test.fas --evalue 0.001 --score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype proteins --tax_scope auto --target_orthologs all --go_evidence non-electronic --override```
Which I modified from the output files of an online EggNOG search.

Strangely, the program runs without error, but I get '0 queries scanned', and an empty table for the *annotations file, and an empty *hits file:
[Schmed_test.emapper.seed_orthologs.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053903/Schmed_test.emapper.seed_orthologs.txt)
[Schmed_test.emapper.annotations.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053904/Schmed_test.emapper.annotations.txt)
[Schmed_test.emapper.hits.txt](https://github.com/eggnogdb/eggnog-mapper/files/9053905/Schmed_test.emapper.hits.txt)

I did an eggNOG run with the web app, and it seems to work just fine:
<img width="945" alt="Eggnog_online_results" src="https://user-images.githubusercontent.com/49084975/177529254-789805fb-6208-4b75-9677-79fa9261537f.png">

I tried checking whether the problem was the special characters in the sequence name, but kept getting the same results, and I haven't been able to find a solution so far. I do need these results, but because I'm doing it on a large set of sequence alignments, I would prefer if I didn't have to complete with the online version.

Also, I might be missing something, as this is the first time I work with emapper.

Thanks for any help.

-carlos

**Comment by Cantalapiedra** [comment]
Hi @carlosj-rr ,

A fast guess: maybe one of your queries is not getting hits from the diamond search, as in https://github.com/eggnogdb/eggnog-mapper/issues/381.

If this is the case, you may try increasing diamond sensitivity, to try to obtain a hit for the missing query.

If this is not the case, I will take a closer look at your data.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @carlosj-rr ,

With increasing sensitivity I meant some of the options here https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#Diamond_search_options

Mainly `--sensmode`. But what you did of reducing the alignment thresholds is OK also, and it worked, so ... happy for you and thank you! :)

Best,
Carlos

ps.: and yes, you are right, we should improve the output messages, like "number of sequences scanned", because it is misleading.
