### ISSUE TITLE
Make a pkl

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#4]
Dear jhcepas, I want to include my own database and I only lack a pkl file, how can I make it?.

regards

**Comment by jhcepas** [comment]
pkl should not be necessary when using custom databases. 
This is a feature currently implemented in the development branch (https://github.com/jhcepas/eggnog-mapper/tree/develop)
We are working now on tests and documentation, but feel free to test: 
```
eggnog_mapper.py seqs.fa --db my_hmm_database.hmm
```
or, if the database is very large and memory cache makes sense: 
```
eggnog_mapper.py seqs.fa --db my_hmm_database.hmm --usemem --cpu 10
```
