### ISSUE TITLE
Not getting outputs from server mode?

### ISSUE THREAD

**Issue by spencerhb** [jhcepas/eggnog-mapper#41]
I run the following command in one terminal:
python emapper.py -d bact --cpu 10 --servermode

Then I run a python script that calls subprocess and the command:
python emapper.py -d bact:localhost:51500 -i file -o outfile

I have 330 files to process so my script just subs in the file and outfile name for each file in the directory:
(for file in directory: do command) I know the command works as I tried it manually before running it in the program. 

I get the typical Sequence mapping starts now!

And then when the script has finished the process for all the files, there is no output to be seen. When I ran just the diamond or just the hmmr search from my command line, I was getting output, the process was just far too slow. 

Any thoughts why I'm getting no results?

**Comment by jhcepas** [comment]
This is weird. If the emapper commands work individually, the problem should be on your bash code. Is outfile name is being changed?  perhaps the output file being written in a different directory?

**Comment by spencerhb** [comment]
This is my script:

import os
import subprocess
import sys

if len(sys.argv)<2:
    print "USAGE: requires python directory. "
    sys.exit()

directory = sys.argv[1]


for files in os.listdir(directory):
    outfile= files[:-3] + 'out'
    if files.endswith('.faa'):
        print files
        cmd = ['python',  'emapper.py', '-d', 'bact:localhost:51500','-i',files, '-o', outfile ]
        print cmd
        subprocess.call(cmd)
print 'Done'


As yu can see the outfile name is being changed. It takes the orginal file names (which start looking like this: 562.7257.PATRIC.faa) subtracts the faa, adds out at the end and  places it in the same directory. I used the same naming convention  in my individual Hmmr searches with no issue. This certainly seems to be a emapper issue.

**Comment by jhcepas** [comment]
I tried your approach and cannot reproduce the problem. This is what I tried in an Ipython terminal: 

```
$ ipython

In [1]: import subprocess

In [2]: cmd = 'python emapper.py -i test/polb.fa -d bact:localhost:51500 -o kk/test2 --override'.split()

In [3]: subprocess.call(cmd)
#  emapper-0.99.2-1-g7245490
# ./emapper.py  -i test/polb.fa -d bact:localhost:51500 -o kk/test2 --override
DB Server already running or not needed!
Reading idmap eggnog-mapper-latest/data/hmmdb_levels/bact_50/bact_50.hmm.idmap
159207 names loaded
Sequence mapping starts now!
 Processed queries:1 total_time:0.343846082687 rate:2.91 q/s
Hit refinement starts now
 Processed queries:1 total_time:11.6238520145 rate:0.09 q/s
Reading HMM matches
Functional annotation of refined hits starts now
 Processed queries:1 total_time:0.110484838486 rate:9.05 q/s
Done
   kk/test2.emapper.hmm_hits
   kk/test2.emapper.seed_orthologs
   kk/test2.emapper.annotations
Total time: 12.9049 secs

In [4]: ls -l kk
total 12
-rw-r--r--. 1 huerta bork 1389 Apr 25 16:04 test2.emapper.annotations
-rw-r--r--. 1 huerta bork  394 Apr 25 16:04 test2.emapper.hmm_hits
-rw-r--r--. 1 huerta bork  319 Apr 25 16:04 test2.emapper.seed_orthologs

**Comment by spencerhb** [comment]
My process never gets to the stage that says:

Processed queries:1 total_time:0.343846082687 rate:2.91 q/s
Hit refinement starts now
 Processed queries:1 total_time:11.6238520145 rate:0.09 q/s
Reading HMM matches
Functional annotation of refined hits starts now
 Processed queries:1 total_time:0.110484838486 rate:9.05 q/s

**Comment by jhcepas** [comment]
Does it work if you don't use server mode? i.e. `-d bact`

**Comment by spencerhb** [comment]
Very very slowly. I usually am detached as it runs. It has made output files though.

**Comment by jhcepas** [comment]
Then I guess is a communication issue between the server and the client emapper. Have you tried in a different machine? I cannot manage to reproduce the problem on my side

**Comment by spencerhb** [comment]
I'm trying it on a different machine and it's moved on after saying Sequencing mapping starts now!  

It now says this:

4026 2223.54607391 1.81 q/s
4051 2237.0793705 1.81 q/s
4076 2249.7980032 1.81 q/s
4101 2272.10814452 1.80 q/s
4126 2284.53296638 1.81 q/s
4151 2299.72098064 1.81 q/s
4176 2306.71686983 1.81 q/s
4201 2315.4298315 1.81 q/s
4226 2331.33472705 1.81 q/s
4251 2341.46965313 1.82 q/s
4276 2356.39471602 1.81 q/s
4301 2370.34750032 1.81 q/s
4326 2390.07512188 1.81 q/s

**Comment by spencerhb** [comment]
The process has finished running. There are not only no output files, but the process seems to have overwritten some of the previous hit files produced by running the program not on server mode.
