### ISSUE TITLE
How can I know which species a anotated GO term is from?

### ISSUE THREAD

**Issue by gouwei1** [jhcepas/eggnog-mapper#411]
Hi,

I'm using EggNOG-mapper to conduct GO functional annotation. I was wonderring how to find the original sequence corresponding to the annotated GO. Could you tell me where to obtain the information?

Best,
Wei

**Comment by Cantalapiedra** [comment]
Hi @gouwei1,

Unfortunately, I don't have access to the original mappings of eggNOG 5 proteins to the reference DBs.

The original sequence should be very close to the eggNOG 5 protein which is annotated with the GO term, likely within 99-100% identity.

Sorry for not being of much help on this issue.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I am not sure, but maybe some of the files here http://eggnog5.embl.de/download/eggnog_5.0/id_mappings/uniprot/ may be of help. If I am not mistaken, GO annotations are transferred from the Uniprot hits.

**Comment by gouwei1** [comment]
Thanks for your reply! The files in  http://eggnog5.embl.de/download/eggnog_5.0/id_mappings/uniprot/ seem not the information I want...

Here's the situation. I got an interesting predicted GO term for a gene using eggnog, but I can not find which species and gene in the database that have been reported having that function in the uniprot database. I'm picking candidate genes for downstream gene knockout experiment, which is very time consuming, so I want more evidance to support that.

The original evidance of the annotation is very important for us who are seeking for candidate genes, so I really hope the infomation is accessable. Is there any other solution ? 

Best,
Wei

**Comment by Cantalapiedra** [comment]
So if you search for your sequence on uniprot you have no hits? Or the hits lack the GO term?
Ideally, you should be able to find the uniprot hit, and from there maybe the organism, publications, etc

**Comment by gouwei1** [comment]
For example, the pep below was annotated having the term 'response to cytokinin stimulus' (GO:0009735) at http://eggnog-mapper.embl.de/, while blast results using uniprot (swissprot) database as ref do not have any genes annotated with that term even though the evalue was set to 1.

Here's the pep:
MLGFFLLQVDEKLRDRVANSVKMGAKVFLVAFFISSLLFPLAFSTSNDGLFRIGLKKIKFDQNNRHAAHLESKEREAASIRKYNLGGNLGASEDTDIVALKNYMDAQYFGEIGVGTPPQKFTVIFDTGSSNLWVPSAKCYFSVPCLFHSKYKSSQSSTYKKNGTSAAIRYGTGAISGFFSQDNVKVGDLVVKNQEFIEATREPSVTFLVAKFDGILGLGFREISVGNAVPVWDNMVKQGLVKEPVFSFWLNRNTEEEKGGEIVFGGVDPNHFRGKHTYVPVTRKGYWQFDMGDVLIGGEPTGVCAGKCSAIADSGTSLLAGPTTVITMINHAIGAAGVVSQQCKAVVQQYGQTILDMLLTEAHPKKVCSQAGLCTFDGTRGVSMGIESVVDEQAGKSSGLHDAMCSACEMAVVWMQNQLRQNQTQERILNYVNELCERLPSPMGQSAVDCRKLSGMPIVSFTIGGKTFDLTPEEYILKVGEGPAAQCISGFAALDIPPPRGPLWILGDVFMGRYHTVFDSGKLRVGFAEAA

**Comment by Cantalapiedra** [comment]
To which eggNOG OGs was assigned?

**Comment by gouwei1** [comment]
Sorry, here are all results:

gene7024	4081.Solyc02g080880.2.1	0.0	951.0	KOG1339@1|root,KOG1339@2759|Eukaryota,37K8V@33090|Viridiplantae,3G8Z4@35493|Streptophyta,44IBU@71274|asterids	35493|Streptophyta	O	Belongs to the peptidase A1 family	-	GO:0003674,GO:0003824,GO:0004175,GO:0004190,GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO:0005773,GO:0005829,GO:0005911,GO:0006508,GO:0006807,GO:0006950,GO:0006970,GO:0008150,GO:0008152,GO:0008233,GO:0009056,GO:0009057,GO:0009506,GO:0009628,GO:0009651,GO:0009719,GO:0009725,GO:0009735,GO:0010033,GO:0010035,GO:0010038,GO:0016787,GO:0019538,GO:0030054,GO:0030163,GO:0042221,GO:0043170,GO:0043226,GO:0043227,GO:0043229,GO:0043231,GO:0044238,GO:0044424,GO:0044444,GO:0044464,GO:0046686,GO:0050896,GO:0055044,GO:0070001,GO:0070011,GO:0071704,GO:0140096,GO:1901564,GO:1901565,GO:1901575	3.4.23.40,3.4.23.5	ko:K01379,ko:K08245	ko04071,ko04140,ko04142,ko04210,ko04915,ko05152,map04071,map04140,map04142,map04210,map04915,map05152	-	-	-	ko00000,ko00001,ko01000,ko01002,ko04147	-	-	-	Asp,SapB_1,SapB_2

**Comment by Cantalapiedra** [comment]
I guess is it ENOG5037K8V? In eggnogdb.embl.de it shows that a single protein out of 306 OG members is annotated with such GO term (response to cytokinin stimulus), which is classified as IDA (Inferred from Direct Assay). 

Maybe you could try to download the OG data (sequence, MSA, tree, hmms, etc) from http://eggnog5.embl.de/#/app/downloads and do a specific search of your sequence against the OG members.

I will take a look at the eggnog-mapper sqlite database to see if I can extract some further info.

**Comment by Cantalapiedra** [comment]
> Sorry, here are all results:
> 
> gene7024 4081.Solyc02g080880.2.1 0.0 951.0 KOG1339@1|root,KOG1339@2759|Eukaryota,37K8V@33090|Viridiplantae,3G8Z4@35493|Streptophyta,44IBU@71274|asterids 35493|Streptophyta O Belongs to the peptidase A1 family - GO:0003674,GO:0003824,GO:0004175,GO:0004190,GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO:0005773,GO:0005829,GO:0005911,GO:0006508,GO:0006807,GO:0006950,GO:0006970,GO:0008150,GO:0008152,GO:0008233,GO:0009056,GO:0009057,GO:0009506,GO:0009628,GO:0009651,GO:0009719,GO:0009725,GO:0009735,GO:0010033,GO:0010035,GO:0010038,GO:0016787,GO:0019538,GO:0030054,GO:0030163,GO:0042221,GO:0043170,GO:0043226,GO:0043227,GO:0043229,GO:0043231,GO:0044238,GO:0044424,GO:0044444,GO:0044464,GO:0046686,GO:0050896,GO:0055044,GO:0070001,GO:0070011,GO:0071704,GO:0140096,GO:1901564,GO:1901565,GO:1901575 3.4.23.40,3.4.23.5 ko:K01379,ko:K08245 ko04071,ko04140,ko04142,ko04210,ko04915,ko05152,map04071,map04140,map04142,map04210,map04915,map05152 - - - ko00000,ko00001,ko01000,ko01002,ko04147 - - - Asp,SapB_1,SapB_2

exactly, that is the OG

**Comment by Cantalapiedra** [comment]
Maybe also some publications could be responsible for the original annotation of the function:

https://scholar.google.es/scholar?q=aspartic+proteinase+response+cytokinin+stimulus&hl=es&as_sdt=0&as_vis=1&oi=scholart

**Comment by Cantalapiedra** [comment]
Also, in http://eggnog5.embl.de/#/app/results, if you look for the OG (e.g. ENOG503G8Z4), there is a "Download" tab where you could download the OG data to compare your query to the OG members.

But let me check if I find the member with the GO term annotation ...

**Comment by Cantalapiedra** [comment]
https://thebiogrid.org/22980/summary/arabidopsis-thaliana/apa1.html

**Comment by Cantalapiedra** [comment]
It is definitely annotated as such: https://phytozome-next.jgi.doe.gov/report/gene/Athaliana_TAIR10/AT1G11910
but I cannot find the publication which annotated the GO term to it.

**Comment by gouwei1** [comment]
Thanks for the kind help! That really solved my problem！By the way, should I search all OGs in the database ? (in this example the OGs include all of them? : KOG1339@1|root,KOG1339@2759|Eukaryota,37K8V@33090|Viridiplantae,3G8Z4@35493|Streptophyta,44IBU@71274|asterids 35493|Streptophyta)

**Comment by gouwei1** [comment]
OK, thank you for that. I have no other problems at present.

**Comment by Cantalapiedra** [comment]
Thank you @gouwei1
