### ISSUE TITLE
Select best OG from output table

### ISSUE THREAD

**Issue by StefanReuscher** [jhcepas/eggnog-mapper#42]
Dear All,

First congrats for the emapper tool. It is fast, delivers comprehensive results (as far is I checked) and the website look like it has great potential.

I have ran emapper with about 26,000 rice proteins and standard settings and got about 90% assigned. Now from the output, how can I proceed ? Specifically I want to put human readable terms on my proteins

There are six OGs for each of the identified proteins ? I understand that in the download sections there are mapping files for each of the @xyzNOGs. But which of those is the best OG ? There must be some kind of score or hierarchy to choose from. Or maybe via the seed ortholog ?

Gruß,

Stefan

**Comment by jhcepas** [comment]
Hi Stefan,
thanks for your message. If you used diamond mode, it will be hard to
predict which is the best OG. You could take the most specific one (i.e.
the one belonging to the most specific taxonomic level). The last one in
the list if I recall correctly.

**Comment by StefanReuscher** [comment]
Just a follow up.

I did select the most specific OG (by taxonomy level) and it seemed to make sense, at least the cases that I checked. I am still amazed by the speed and the coverage of terms. About 85% of all proteins have a human readable annotation now.
