### ISSUE TITLE
Add KO modules as annotation source

### ISSUE THREAD

**Issue by jhcepas** [jhcepas/eggnog-mapper#43]
This is ongoing.

**Comment by rohansachdeva** [comment]
KO annotations would be awesome!

Just curious if you have any thoughts on when they will be added? Just something rough would be really helpful. A couple weeks? A month? Or longer? I know it's hard to estimate these things so I won't hold you to anything :)

**Comment by jhcepas** [comment]
I am kind of keeping 12th of May as an internal deadline for this, as it is needed for another project, but cannot promise it too hard  :)

**Comment by MarisaMiller** [comment]
I think my question is related to this as well. I am wondering how the map numbers I obtained with eggnog-mapper (like map00100) can be used as an entry point into any of the KEGG analysis tools on the KEGG website (http://www.kegg.jp/kegg/mapper.html).

I would like to use the KEGG information to compare against another organism in the KEGG database, but it's unclear to me how these annotations can be used to do that.

**Comment by hevronig** [comment]
Any update on this feature? pretty please... ;)

**Comment by jhcepas** [comment]
merged with #64
