### ISSUE TITLE
Way to run diamond on multiple threads?

### ISSUE THREAD

**Issue by spencerhb** [jhcepas/eggnog-mapper#47]
Is there a way to run diamond searches on multiple threads?

**Comment by jhcepas** [comment]
yes, if you use --cpu XX, diamond will be launched with multithreading option.

**Comment by spencerhb** [comment]
So I actually tried that and I got a syntax error and that I don't get when
I run a regular diamond search without multiple threads.

**Comment by jhcepas** [comment]
That flag seems to run on the systems we have tried (and currently working on the online service). I would need more context to reproduce the problem

**Comment by spencerhb** [comment]
This is the command that I use and I have attached a screen capture of the
output.

python -i genbatch1.faa --output batch1out --cpu 10 -m diamond

**Comment by spencerhb** [comment]
I also ran this file online with no problem however I found that online
some of the columns in the annotation output specifically J K&L when viewed
in Excel were listed as 'NA' vs when I ran it through the downloaded
version of Emapper. Which is why I'm trying to run it again on my
downloaded version.
