### ISSUE TITLE
Update diamond DB

### ISSUE THREAD

**Issue by davidvilanova** [jhcepas/eggnog-mapper#48]
Hello,
I´m running diamond 0.38 and getting a problem with the default eggNOD diamond db

`Error: Database was built with a different version of diamond as is incompatible.
`
Do you have the link to the same diamond file in fasta file so i can recompile the db.

Thanks,
david

**Comment by jhcepas** [comment]
Did you tried the version here: https://github.com/jhcepas/eggnog-mapper/tree/master/bin

**Comment by davidvilanova** [comment]
I know this is a solution but i´m using diamond for other applications and would be much better to work with one single version (that i keep up to date)
Thanks

**Comment by jhcepas** [comment]
I see. I will upload the raw fasta file somewhere and make it available if that helps.

**Comment by davidvilanova** [comment]
Thanks so much Jaime.

**Comment by ealdraed** [comment]
Hello @davidvilanova!

> I´m running diamond 0.38 and getting a problem with the default eggNOD diamond db

Am I right, that you actually meant v0.8.38?! I just tried this version and it works with the downloaded `eggnog_proteins.dmnd`. If you get such an error, I suppose you have a 0.9.x version, as this requires rebuilding of the database.

But there is a simple solution to this. Run these piped commands:
`/path/to/bundled/diamond getseq --db eggnog_proteins.dmnd | /path/to/v9/diamond makedb --db eggnog_proteins_v9`

Or one after the other:
`/path/to/bundled/diamond getseq --db eggnog_proteins.dmnd > eggnog_proteins.faa`
 `/path/to/v9/diamond makedb --in eggnog_proteins.faa --db eggnog_proteins_v9`
`rm eggnog_proteins.faa`

Regards

**Comment by jhcepas** [comment]
Still needing this? 
the raw file used to generate the diamond db is at: http://eggnogdb.embl.de/download/eggnog_4.5/eggnog-mapper-data/eggnog4.clustered_proteins.fa.gz

**Comment by nhungdoan1905** [comment]
@ealdraed 
i still can not solve this problem
./diamond getseq --db /home/vdsa/miniconda3/envs/eggnog-mapper/lib/python3.8/site-packages/data/eggnog_proteins.dmnd > eggnog_proteins.faa
Error: Database was built with a different version of diamond as is incompatible.

**Comment by Cantalapiedra** [comment]
Hi @nhungdoan1905 ,

please, answer in the other issue where you wrote what are your emapper.py and diamond versions:
emapper.py --version
diamond --version

Thank you.

Best,
Carlos
