### ISSUE TITLE
Speed increase with hmmsearch?

### ISSUE THREAD

**Issue by rohansachdeva** [jhcepas/eggnog-mapper#50]
Hi - I think eggnog-mapper could get a pretty good speed increase with a simple switch to hmmsearch from hmmscan. Please, see the following: https://cryptogenomicon.org/2011/05/27/hmmscan-vs-hmmsearch-speed-the-numerology/

Although I think the E-values will differ which could muck things up.

**Comment by jhcepas** [comment]
thanks @rohansachdeva. the recommended execution for hmm-based searching is with via `--usemem`, which uses a method that is actually faster than both hmmsearch and hmmscan. 
But it is true we could switch to hmmsearch when disk-based searches are used (although it will be very slow when using large DBs like euk or bact)
