### ISSUE TITLE
server stopped working since 6/6/2024

### ISSUE THREAD

**Issue by Venetios** [jhcepas/eggnog-mapper#515]
My job is usally completed after 4 to 5 mins. Now it runs for days. My jobs arent completed since 6/6/2024, as the server status shows jobs beeing processed from that specific date. Currurt date 11/6/2024

**Comment by kcallicott** [comment]
I'll second this.  I think my normal run is more like 30 minutes, but my last successful submission was 6/4.  Since then, jobs list as "started" but don't complete.

**Comment by True-Create** [comment]
When will the server be restored approximately?

**Comment by Cantalapiedra** [comment]
Hi,

Thank you for reporting this.
I cannot give an estimation of when the problem will be solved, but we hope to do it ASAP.

Sorry for the inconveniences and thank you for your patience.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Please, check issue #511
