### ISSUE TITLE
eggNOG-mapper online server have problem

### ISSUE THREAD

**Issue by True-Create** [jhcepas/eggnog-mapper#517]
Some users have encountered job congestion issues while using the eggNOG-mapper online server.

The file GWHBHQB00000000.Protein.fasta was submitted by the user ***@qq.com, containing 49,632 sequences, and was submitted on 2024-06-06. The current status is "Running," having been running for 12 hours and 25 minutes. There are currently 2 jobs in the queue waiting to be processed, with each job containing 99,264 sequences.

The file Chi_protein.fasta was submitted by the user ***@upf.edu, containing 42,653 sequences, and was submitted on 2024-05-24. The current status is "Running," having been running for 12 days, 16 hours, 27 minutes, and 19 seconds (note that the format here might be days-hours:minutes:seconds). There are currently 13 jobs in the queue waiting to be processed, with each job containing 509,875 sequences.

**Comment by Cantalapiedra** [comment]
Dear @True-Create ,

Yes, the server is not working properly, and it is down now for maintenance. I will report back once that it is up and running again.

Thank you for reporting this.

Best,
Carlos

**Comment by True-Create** [comment]
Thank you very much for your answer.

**Comment by Cantalapiedra** [comment]
Please, check issue #511

**Comment by Maheswari6269** [comment]
eggnogmapper is not working, its showing 502 Bad gateway. when this problem will get solved? please help. I need this tool urgently

**Comment by Cantalapiedra** [comment]
> eggnogmapper is not working, its showing 502 Bad gateway. when this problem will get solved? please help. I need this tool urgently

We cannot know for sure when it will get solved. It depends on the infrastructure we use to serve eggNOG-mapper web. Sorry for the inconveniences. Please, check issue #511 for updates on this.

**Comment by Maheswari6269** [comment]
Thank you for your response. I understand that the issue depends on the
infrastructure, and I appreciate your efforts in resolving it. I will keep
an eye on issue #511 for updates. However, I urgently need eggNOG-mapper
for my analysis. Could you suggest any alternative methods or local
installation options in the meantime?"

**Comment by Cantalapiedra** [comment]
> Thank you for your response. I understand that the issue depends on the
> infrastructure, and I appreciate your efforts in resolving it. I will keep
> an eye on issue [#511](https://github.com/eggnogdb/eggnog-mapper/issues/511) for updates. However, I urgently need eggNOG-mapper
> for my analysis. Could you suggest any alternative methods or local
> installation options in the meantime?"
> […](#)

You may try to install it locally, yes. https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.12

**Comment by Maheswari6269** [comment]
Thank you so much. The website is working now

**Comment by Cantalapiedra** [comment]
Yes, it is working. Just testing whether it is stable now or not

**Comment by Maheswari6269** [comment]
Glad! It works. Thank you once again.

**Comment by Cantalapiedra** [comment]
Glad that it worked for you! So far it seems stable.

**Comment by Maheswari-dasgupta** [comment]
The eggNOG-mapper server is currently not working and returns a 504 Bad Gateway error. When is the service expected to be restored?

**Comment by gaumondhelin-gif** [comment]
eggNOG-mapper 服务器目前无法工作，并返回 504 错误网关错误。预计什么时候恢复服务？
