### ISSUE TITLE
EggNog evalue and score

### ISSUE THREAD

**Issue by Zara-Ahmad** [jhcepas/eggnog-mapper#518]
Hi, I want to ask about the evalue and score when we use eggnog mapper. What is the the score and e value signify.

I am annotating the WGS using EGGNOC mapper with each gene i get this score can you please tell me what is this score is is about. How should i interperate it amd what is the init for this. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/zarkha/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/zarkha/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

#query | seed_ortholog | evalue | score | eggNOG_OGs | max_annot_lvl | COG_category | Description | Preferred_name | GOs | EC | KEGG_ko | KEGG_Pathway | KEGG_Module | KEGG_Reaction | KEGG_rclass | BRITE | KEGG_TC | CAZy | BiGG_Reaction | PFAMs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
assembly_contig_1_1 | 1201292.DR75_517 | 1.39e-191 | 532.0 | COG3711@1\|root,COG3711@2\|Bacteria,1TT5A@1239\|Firmicutes,4HC5Y@91061\|Bacilli,4B1PC@81852\|Enterococcaceae | 91061\|Bacilli | K | CAT RNA binding domain | sacT | - | - | ko:K03488 | - | - | - | - | ko00000,ko03000 | - | - | - | CAT_RBD,PRD
assembly_contig_1_2 | 226185.EF_1516 | 0.0 | 1267.0 | COG1263@1\|root,COG1264@1\|root,COG2190@1\|root,COG1263@2\|Bacteria,COG1264@2\|Bacteria,COG2190@2\|Bacteria,1TPJ8@1239\|Firmicutes,4HA8X@91061\|Bacilli,4AZ9R@81852\|Enterococcaceae | 91061\|Bacilli | G | phosphotransferase system, EIIB | nagE | - | 2.7.1.193,2.7.1.199 | ko:K02802,ko:K02803,ko:K02804,ko:K20116,ko:K20117,ko:K20118 | ko00010,ko00520,ko02060,map00010,map00520,map02060 | M00267,M00809 | R02738,R05199 | RC00017,RC03206 | ko00000,ko00001,ko00002,ko01000,ko02000 | 4.A.1.1.13,4.A.1.1.14,4.A.1.1.15,4.A.1.1.2,4.A.1.1.5,4.A.1.1.7,4.A.1.1.9 | - | iSB619.SA_RS08720 | PTS_EIIA_1,PTS_EIIB,PTS_EIIC
assembly_contig_1_3 | 1201292.DR75_519 | 0.0 | 924.0 | COG3711@1\|root,COG3711@2\|Bacteria,1TSGM@1239\|Firmicutes,4HB3W@91061\|Bacilli,4B0I0@81852\|Enterococcaceae | 91061\|Bacilli | K | PRD domain | - | - | - | ko:K02538 | - | - | - | - | ko00000,ko03000 | - | - | - | HTH_11,Mga,PRD,PTS_IIB
assembly_contig_1_4 | 1201292.DR75_520 | 2.83e-92 | 271.0 | COG1762@1\|root,COG1762@2\|Bacteria,1VIS8@1239\|Firmicutes,4HPYD@91061\|Bacilli,4B2S6@81852\|Enterococcaceae | 91061\|Bacilli | G | Phosphoenolpyruvate-dependent sugar phosphotransferase system, EIIA 2 | - | - | - | ko:K02806 | ko02060,map02060 | - | - | - | ko00000,ko00001,ko01000,ko02000 | - | - | - | PTS_EIIA_2
assembly_contig_1_5 | 1201292.DR75_521 | 1.94e-64 | 197.0 | COG1445@1\|root,COG1445@2\|Bacteria,1VASC@1239\|Firmicutes,4HKYF@91061\|Bacilli,4B2ZB@81852\|Enterococcaceae | 91061\|Bacilli | G | IIB component | - | - | 2.7.1.202 | ko:K02769 | ko00051,ko01100,ko01120,ko02060,map00051,map01100,map01120,map02060 | M00273 | R03232 | RC00017,RC03206 | ko00000,ko00001,ko00002,ko01000,ko02000 | 4.A.2.1 | - | - | PTS_IIB
assembly_contig_1_6 | 1201292.DR75_522 | 3.61e-99 | 288.0 | COG1762@1\|root,COG1762@2\|Bacteria,1V5TG@1239\|Firmicutes,4HHQJ@91061\|Bacilli,4B1TR@81852\|Enterococcaceae | 91061\|Bacilli | G | Phosphoenolpyruvate-dependent sugar phosphotransferase system, EIIA 2 | - | - | 2.7.1.202 | ko:K02768 | ko00051,ko01100,ko01120,ko02060,map00051,map01100,map01120,map02060 | M00273 | R03232 | RC00017,RC03206 | ko00000,ko00001,ko00002,ko01000,ko02000 | 4.A.2.1 | - | - | PTS_EIIA_2
assembly_contig_1_7 | 1201292.DR75_523 | 8.05e-215 | 598.0 | COG1299@1\|root,COG1299@2\|Bacteria,1TPKU@1239\|Firmicutes,4H9XS@91061\|Bacilli,4B0GZ@81852\|Enterococcaceae | 91061\|Bacilli | G | Phosphotransferase system, EIIC | - | - | - | ko:K02770 | ko00051,ko01100,ko01120,ko02060,map00051,map01100,map01120,map02060 | M00273 | R03232 | RC00017,RC03206 | ko00000,ko00001,ko00002,ko02000 | 4.A.2.1 | - | - | PTS_EIIC
assembly_contig_1_8 | 1201292.DR75_524 | 1.15e-166 | 465.0 | COG0036@1\|root,COG0036@2\|Bacteria,1TT1C@1239\|Firmicutes,4HDTC@91061\|Bacilli,4AZPN@81852\|Enterococcaceae | 91061\|Bacilli | G | Ribulose-phosphate 3 epimerase family | alsE | - | - | ko:K17195 | ko00051,ko01120,map00051,map01120 | - | R09031 | RC03111 | ko00000,ko00001,ko01000 | - | - | - | Ribul_P_3_epim
assembly_contig_1_9 | 1201292.DR75_525 | 1.92e-144 | 407.0 | COG0741@1\|root,COG0741@2\|Bacteria,1V6X7@1239\|Firmicutes,4HJEB@91061\|Bacilli,4B21X@81852\|Enterococcaceae | 91061\|Bacilli | M | Lysozyme-like | pvaA | - | - | - | - | - | - | - | - | - | - | - | Lysozyme_like
assembly_contig_1_10 | 1201292.DR75_526 | 0.0 | 1449.0 | COG0474@1\|root,COG0474@2\|Bacteria,1TPF5@1239\|Firmicutes,4H9ZI@91061\|Bacilli,4AZQQ@81852\|Enterococcaceae | 91061\|Bacilli | P | E1-E2 ATPase | ctpE | - | - | ko:K12952 | - | - | - | - | ko00000,ko01000 | 3.A.3.23 | - | - | E1-E2_ATPase,Hydrolase
assembly_contig_1_11 | 1201292.DR75_527 | 0.0 | 1219.0 | COG0358@1\|root,COG0358@2\|Bacteria,1TQ0X@1239\|Firmicutes,4HAG2@91061\|Bacilli,4B0UE@81852\|Enterococcaceae | 91061\|Bacilli | K | RNA polymerase that catalyzes the synthesis of short RNA molecules used   as primers for DNA polymerase during DNA replication | dnaG | - | - | ko:K02316 | ko03030,map03030 | - | - | - | ko00000,ko00001,ko01000,ko03032 | - | - | - | DnaB,DnaB_bind,Toprim_2,Toprim_4,Toprim_N,zf-CHC2
assembly_contig_1_12 | 1201292.DR75_528 | 1.55e-252 | 694.0 | COG0568@1\|root,COG0568@2\|Bacteria,1TPD6@1239\|Firmicutes,4HB1H@91061\|Bacilli,4AZDR@81852\|Enterococcaceae | 91061\|Bacilli | K | Sigma factors are initiation factors that promote the attachment of RNA   polymerase to specific initiation sites and are then released. This sigma   factor is the primary sigma factor during exponential growth | sigA | - | - | ko:K03086 | - | - | - | - | ko00000,ko03021 | - | - | - | Sigma70_r1_1,Sigma70_r1_2,Sigma70_r2,Sigma70_r3,Sigma70_r4

</body>

</html>

Thank you so much. 
Best, Zara

**Comment by Cantalapiedra** [comment]
Dear @Zara-Ahmad ,

If you are using the default pipeline or the web, these values are from diamond. You may find more info within diamond documentation, for instance: https://github.com/bbuchfink/diamond/wiki/1.-Tutorial#protein-alignment

Best,
Carlos
