### ISSUE TITLE
What are the origins of the Gene Names?

### ISSUE THREAD

**Issue by nextgenusfs** [jhcepas/eggnog-mapper#52]
Hi @jhcepas, great job on eggnog and the new mapper utility.  I'm interested in using the results from eggnog-mapper for some automated functional annotation as part of my genome annotation tool.  I'm curious where you are pulling the Gene Names from in the eggnog-mapper annotations output, are they all UniProtKB gene names?  I'm working on trying to curate a mapping file of gene names to product definitions that will pass GenBank annotation rules.  The eggnog descriptions are useful, but most would not pass GenBank submission requirements.  Basically I'd just like to know where you are getting the names from so I can cross reference to make sure I'm recovering the proper product definition. I'd like to avoid doing another sequence alignment based check if I can.
Thanks,
Jon

**Comment by jhcepas** [comment]
predicted gene names are the consensus of names among orthologs. Those names are, in most cases HUGO names, but they could also come from other sources. Sequence names in eggnog are not always UniprotKB, there are also Ensembl, RefSeq, etc. Depending on the source proteome we used. 
All current name conversions can be downloaded from here: http://eggnogdb.embl.de/download/eggnog_4.5/eggnog4.protein_id_conversion.tsv.gz 
 
There are also more up to date mappings to uniprot: http://eggnogdb.embl.de/download/eggnog_4.5/id_mappings/uniprot/
