### ISSUE TITLE
Partial descriptions in eggNOG db

### ISSUE THREAD

**Issue by tgurbich** [jhcepas/eggnog-mapper#520]
Hello! I've noticed that there seem to be some description parsing issues in the eggNOG database. Not sure where best to report it so adding here, sorry if this isn't the best place or it is already a known issue. 

Looking at column 4 [in this file](http://eggnog5.embl.de/download/eggnog_5.0/e5.og_annotations.tsv), here are a few examples:

- some partial strings as descriptions, for example, "`Atpase (Aaa`", `"SAM)-dependent`", "`protein domain associated with`", "`zinc metalloprotease whose natural substrate is`", "`acid) synthase`", "`implicated in the recycling of the`", "`with signal peptide and GMGPP repeat at`", 
- many descriptions begin with "to ", "which ", "thus ", seems like these are partial sentences. For example, "`to Saccharomyces cerevisiae CDC8 (YJR057W)`", "`to N amino acid permease`", "`to Escherichia coli, Escherichia coli O6, and Escherichia coli O157 H7 DNA-binding protein H-NS SWALL HNS_ECOLI (SWALL P08936) (136 aa) fasta scores E()`", "`which is also found adjacent to an ISCro1 element at`"
- partial long sentences with information sometimes lacking context. Some examples:
"`thus facilitating recognition of the initiation point. It is needed to translate mRNA with a short Shine-Dalgarno (SD) purine-rich sequence`"
"`this blockage is overcome (after 90 minutes) by subsequent expression of antitoxin HicB. Overexpression causes cleavage of a number of mRNAs and tmRNA, in a translation-independent fashion, suggesting this is an mRNA interferase. mRNA interferases play a role in bacterial persistence to antibiotics`"
"`then breaks the thioester bond and releases the atrochrysone carboxylic acid from gedC. The atrochrysone carboxylic acid is then converted to atrochrysone which is further transformed into emodin anthrone. The next step is performed by the`"

I see these in the online version of the database as well.

Best,
Tanya

**Comment by Cantalapiedra** [comment]
Dear @tgurbich ,

Thank you very much for reporting this. Note however that this is an eggNOG DB 5 annotations issue, and not directly with eggNOG-mapper. Unfortunately, I have no means to fix this. I will try to report to the team which crafted those files for eggNOG DB 5.

Sorry for the inconveniences caused by this.

Best,
Carlos
