### ISSUE TITLE
[BUG] wrong version installed when using conda

### ISSUE THREAD

**Issue by rpeguil** [jhcepas/eggnog-mapper#521]
System version: Ubuntu 22.04.4 LTS
Conda version: 24.5.0

Hello,
I wanted to install the last version (2.1.12) of eggnog-mapper using the following command:
`conda install -c bioconda -c conda-forge eggnog-mapper`

It worked well, but it installed the version 2.1.11 instead and not the last release:
```
(eggnog-mapper_2.1.12) odin@odin-PowerEdge-T620:~$ emapper.py -v
emapper-2.1.11 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Diamond version found: diamond version 2.1.9 / MMseqs2 version found: 15.6f452
```
The same happened using mamba instead of conda.

I then tried:
`conda install -c bioconda -c conda-forge eggnog-mapper=2.1.12`

Which worked, but when checking the version, I got the following error message regarding eggnog db:
```
(eggnog-mapper_2.1.12) odin@odin-PowerEdge-T620:~$ emapper.py -v
There was an error retrieving eggnog-mapper DB data: not a valid file "/home/odin/anaconda3/envs/eggnog-mapper_2.1.12/lib/python3.12/site-packages/data/eggnog.db"
Maybe you need to run download_eggnog_data.py
emapper-2.1.12 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: unknown / Diamond version found: diamond version 2.1.9 / MMseqs2 version found: 15.6f452 / Compatible novel families DB version: 1.0.1
```

Is there a known issue with the last release of eggnog-mapper?

thanks

**Comment by meisiy** [comment]
Same issue happened to me. I tried to use mamba install and conda install on my macbook.

**Comment by Cantalapiedra** [comment]
Dear @rpeguil ,

I tried today with the same conda version as yours, and it worked fine to me, installing 2.1.12. I really don't know why it is trying to install 2.1.11 for you, sorry.

Regarding the error message, note that it is just telling you that you need to run the script to download the eggNOG-mapper databases.

Best,
Carlos

**Comment by rpeguil** [comment]
Dear @Cantalapiedra,
Thank you for your reply.
Yes, I downloaded the databases after that.
Best,
