### ISSUE TITLE
eggnog-mapper web not working

### ISSUE THREAD

**Issue by francescodc87** [jhcepas/eggnog-mapper#536]
I tried to use the web version, but it seems that it is not working. I get Server Error (500) after clicking submit.
I just wanted to check if this is a temporary issue on the server side.
Thanks for the help

**Comment by Cantalapiedra** [comment]
Hi,
Thanks for reporting this. Hopefully, it should be working again.
Best,
Carlos

**Comment by francescodc87** [comment]
It is!
thank you very much Carlos
Best wishes,
Francesco
