### ISSUE TITLE
The first is error in my configure.

### ISSUE THREAD

**Issue by lw3259111** [jhcepas/eggnog-mapper#55]
When i download the software following with 
`git clone https://github.com/jhcepas/eggnog-mapper.git`
and download eggnog.db,bactNog.hmm,Pfam-A.hmm into data file.
I conduct 
`python emapper.py -i test/polb.fa --output polb_bact -d data/Pfam-A.hmm 
or 
python emapper.py -i test/polb.fa --output polb_bact -d data/bactNog.hmm`
and get error `#  emapper-0.99.3
# ./emapper.py  -i test/polb.fa --output polb_bac -d data/bactNOG.hmm
Traceback (most recent call last):
  File "emapper.py", line 1086, in <module>
    main(args)
  File "emapper.py", line 218, in main
    host, port, dbpath, scantype, idmap = setup_hmm_search(args)
  File "emapper.py", line 113, in setup_hmm_search
    raise ValueError('Invalid database name/server')
ValueError: Invalid database name/server
`
so i don't know  how to solve to problem.
Please help me,thanks!

**Comment by jhcepas** [comment]
for the eggnog databases, you need to use the name of the database, not the path: 

-d bact
or 
-d bactNOG
