### ISSUE TITLE
Metagenomic HMMs?

### ISSUE THREAD

**Issue by bachev** [jhcepas/eggnog-mapper#58]
Hi there,

is there a way to run emapper.py on all HMMs for everything at once? I do have some metagenomic data with bacteria, fungi and eukaryotic sequences which I would like to have a look via eggnog.

Best,
  Bastien

**Comment by jhcepas** [comment]
You could run against the "NOG" database, but diamond mode should give you
much faster results without really affecting quality.
You can always run the HMM search for sequences that did not produce hits
with diamond.

**Comment by bachev** [comment]
Thanks, will do that.
