### ISSUE TITLE
Please consider using "diamond dbinfo" in next release

### ISSUE THREAD

**Issue by bachev** [jhcepas/eggnog-mapper#60]
Hi there,

like another user of emapper, I ran into the problem that the diamond database distributed with emapper was incompatible with the diamond I had installed locally.

I asked the the author of diamond to implement a dbinfo command, which he did very quickly and starting with 0.9.10, diamond allows to check the database version with that.

Here also: gzip -9 reduces the diamond db by ~40%.

Best,
  Bastien

**Comment by jhcepas** [comment]
thanks for the suggestion, we could also distribute the raw fasta file used to build diamond, in case someone needs to recreate the db

**Comment by bachev** [comment]
I think that distributing the raw FASTA actually makes the most sense. The compressed FASTAs are smaller than diamond DBs, building a diamond DB is comparatively fast, and you would not need to enforce a given diamond version for the user.

I'd go with raw FASTAs as default, yes.

**Comment by ealdraed** [comment]
Hello!

Like I posted in #48, there is actually no problem in converting the distributed diamond DB. You can use the bundled version's `getseq` command to get a *.faa file that you then use as input for your version's `makedb` command.

But I agree with you, that in the future, the release of the raw FASTA files could facilitate things and reduce download size.

**Comment by jhcepas** [comment]
In any case, raw fasta file used to generate the diamond database is available at: 
`http://eggnogdb.embl.de/download/emapperdb-4.5.0/eggnog4.clustered_proteins.fa.gz`
