### ISSUE TITLE
Error: Unrecognized format 

### ISSUE THREAD

**Issue by chen318liang** [jhcepas/eggnog-mapper#62]
I download eggnog-mapper from github, and download the bacteria database with the following command line

python download_eggnog_data.py bact
I then run emapper using the test data:

python emapper.py -i test/polb.fa --output polb_back -d bact

It gives me the following error message:

\#  emapper-0.99.3
\# ./emapper.py  -i test/polb.fa --output polb_bact -d bact
Sequence mapping starts now!

Error: Unrecognized format, trying to open hmm file /public/home/guold/chenl/software/eggnog/eggnog-mapper/data/hmmdb_levels/bact_50/bact_50.hmm for reading.

 Processed queries:1 total_time:0.566287994385 rate:1.77 q/s
Hit refinement starts now
 Processed queries:1 total_time:12.5431919098 rate:0.08 q/s
Reading HMM matches
Functional annotation of refined hits starts now
 Processed queries:0 total_time:0.31346988678 rate:0.00 q/s
Done
   polb_bact.emapper.hmm_hits
   polb_bact.emapper.seed_orthologs
   polb_bact.emapper.annotations
Total time: 14.2532 secs

what is wrong with it?  anyone knows this problem? Thanks very much!!

**Comment by jhcepas** [comment]
It seems you did not download the hmm correctly. Corrupted or missing files?
what do you see when running 
`head /public/home/guold/chenl/software/eggnog/eggnog-mapper/data/hmmdb_levels/bact_50/bact_50.hmm`?

**Comment by chen318liang** [comment]
@jhcepas thanks very much! I used md5sum to check it. The result is below and is same with result you give in other  comment.
$ md5sum *
dec0a42cccd7980df7cf1deba4c67aae  bact_50.hmm.h3f
ff8aa06c3d3feb21eafbb60fdf4545d7  bact_50.hmm.h3i
8b98e662769ba703a54daa30e05f3b79  bact_50.hmm.h3m
13965f23c4e7c746640adc5b829741b6  bact_50.hmm.h3p
83790065e3171e23e9cd3f9a4e48d599  bact_50.hmm.idmap
a26db28c16818c472d787de5c63d5460  bact_50.info
aa1e995a371b1cb17cc6e8f1d06fdb5c  bact_50.pkl 

But when I run the head command, it give me a message : head: can not open /public/home/guold/chenl/software/eggnog/eggnog-mapper/data/hmmdb_levels/bact_50/bact_50.hmm reading data: no this file or directory.
I do not know what is the problem. Could you help me? Thanks very much!

**Comment by jhcepas** [comment]
for same reason, the databases are missing in your installation. how did you download them? 
there is a script to get the files and place them in the correct path.

**Comment by chen318liang** [comment]
@jhcepas My commands is below:

python2.7 download_eggnog_data.py bact &

python emapper.py -i test/polb.fa --output polb_back -d bact

**Comment by jhcepas** [comment]
if the files are there, why this one is missing? `/guold/chenl/software/eggnog/eggnog-mapper/data/hmmdb_levels/bact_50/bact_50.hmm`
(from your previos comments)

**Comment by chen318liang** [comment]
I do not know why  this error appears. But these files  actually exist. 
$ ls -alh
总用量 26G
drwxrwxr-x 2 guold guold 4.0K 10月 14 23:52 ./
drwxrwxr-x 3 guold guold 4.0K 10月 14 18:19 ../
-rw-rw-r-- 1 guold guold 5.4M  7月  1 2016 bact_50.hmm.idmap
-rw-rw-r-- 1 guold guold 9.6M  4月 28 2015 bact_50.pkl
-rw-rw-r-- 1 guold guold 8.3M  4月 28 2015 bact_50.info
-rw-rw-r-- 1 guold guold 9.0M  4月 28 2015 bact_50.hmm.h3i
-rw-rw-r-- 1 guold guold 4.3G  4月 28 2015 bact_50.hmm.h3f
-rw-rw-r-- 1 guold guold 9.9G  4月 28 2015 bact_50.hmm.h3m
-rw-rw-r-- 1 guold guold  12G  4月 28 2015 bact_50.hmm.h3p

**Comment by jhcepas** [comment]
in the right path?
can you run `find data/` and post output?

**Comment by chen318liang** [comment]
Yes, the path is right. when I run find  data/ , it showed a list fa files like this:
data/OG_fasta/delNOG/0GHYN.fa
data/OG_fasta/delNOG/0GF96.fa
data/OG_fasta/delNOG/0GMZE.fa
......
......
data/OG_fasta/delNOG/0GJ6A.fa
data/OG_fasta/delNOG/0GHUZ.fa
data/OG_fasta/delNOG/0GFY8.fa
data/OG_fasta/delNOG/0GMW4.fa
data/OG_fasta/delNOG/0GMR1.fa
data/eggnog_proteins.dmnd

**Comment by jhcepas** [comment]
then I don't know why the `head` command does not find the file...

**Comment by jhcepas** [comment]
sorry, I cannot reproduce the problem... could you try in a different system? what version of emapper are you using?

**Comment by chen318liang** [comment]
I use the command of git clone https://github.com/jhcepas/eggnog-mapper.git to install the emapper. The version is emapper-0.99.3-1-g88a02cf. I try another serve using the same commands, it now running. The version is emapper-0.99.3-11-g9f12b50 now. Why different version was downloaded? Can I choose the special version when downloading it? Thanks very much!

**Comment by jhcepas** [comment]
git clone is giving you the latest development version. If you want to use the latest stable, download from here: https://github.com/jhcepas/eggnog-mapper/releases

**Comment by chen318liang** [comment]
Ok! Thanks very much!
