### ISSUE TITLE
gzip prompts in download_eggnog_data.py

### ISSUE THREAD

**Issue by caleb-easterly** [jhcepas/eggnog-mapper#69]
Hi, 
I have run into this problem a couple of times with `download_eggnog_data.py`, where gzip (gunzip, really), is preventing the script from being completely automated - if the file already exists, gzip will ask for confirmation to overwrite and the script will hang. 

I was thinking of propogating the `-f` argument to gunzip in the download functions; something like

```
cmd = 'cd %s && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog.db.gz %s && echo Decompressing... && gunzip eggnog.db.gz %s' %(get_data_path(), url, force)
```
where `force` is `-f` if  `download_eggnog_data.py` was run with `-f`

I'm happy to work on this, if you like.

**Comment by jhcepas** [comment]
added with PR #71
