### ISSUE TITLE
ERROR 404 when downloading bact database

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#7]
Dear jhcepas, the new version of your mapper are amazing!, I could download all databases (arch, euk, viruses), but bact give me the error (complete sequence):

> Download 1 HMM database(s): bact? [y,n] y
> Downloading bact HMM database " at /home/ecastron/programs/eggnogmapper/data/hmmdb_levels/bact\_hmm ...
> mkdir -p /home/ecastron/programs/eggnog-mapper/data/hmmdb_levels; cd /home/ecastron/programs/eggnog-mapper/data/hmmdb_levels; wget -N -nH --user-agent=Mozilla/5.0 --relative -r --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off http://beta-eggnogdb.embl.de/download/eggnog_4.5/eggnog-mapper-data/hmmdb_levels/euk_50/
> --2016-07-05 15:10:48--  http://beta-eggnogdb.embl.de/download/eggnog_4.5/eggnog-mapper-data/hmmdb_levels/euk_50/
> Resolving beta-eggnogdb.embl.de... 194.94.44.96
> Connecting to beta-eggnogdb.embl.de|194.94.44.96|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2016-07-05 15:10:49 ERROR 404: Not Found.

checking the code, the script search for euk_50, should be bact_50?.

regards

**Comment by jhcepas** [comment]
Indeed, it should be bact_50! I will fix it asap
