### ISSUE TITLE
Nr of input sequences != Nr of output lines?

### ISSUE THREAD

**Issue by karchern** [jhcepas/eggnog-mapper#73]
Hi,

I used the online interface of eggNOG-mapper (DIAMOND, rest standard settings) for functional annotation of approx. 60000 bacterial gene sequences. Curiously, I only retrieved around 47000 lines back.

Am I right in assuming that all gene sequences which are absent in the output file could not have any orthology assigned confidently?

Thank you!

**Comment by jhcepas** [comment]
exactly!
