### ISSUE TITLE
Error using download_eggnog_data.py

### ISSUE THREAD

**Issue by sijisaula** [jhcepas/eggnog-mapper#79]
I'm having some issues doing running the database download script...what could I be missing?:

`$ python download_eggnog_data.py euk`
`      File "download_eggnog_data.py", line 10`
`         print colorify(cmd, 'cyan')`
`                             ^`
`SyntaxError: invalid syntax`

**Comment by jhcepas** [comment]
thanks for reporting, 
this is probably because you are using python 3, which is not yet supported.

**Comment by sijisaula** [comment]
Awesome, thanks for the help!...will revert to python 2.7 versions
