### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Sanrrone** [jhcepas/eggnog-mapper#8]
Dear jhcepas, I have the tree files using -d bact and its ok, but when use viruses db the annotation step crash: 
> python emapper.py -d viruses -i gingi.faa --output eggnogBact --override --cpu 16
> Sequence mapping starts now!
> 26 173.259658337 0.15 q/s
> 51 173.265169144 0.29 q/s
> 76 173.268593311 0.44 q/s
> 101 173.271979332 0.58 q/s
> 126 173.274962902 0.73 q/s
> 151 173.279873848 0.87 q/s
> 176 173.283407927 1.02 q/s
> 201 173.28731966 1.16 q/s
> 226 173.290519714 1.30 q/s
> processed queries:238 total_time:173.292301893 rate:1.37 q/s
> Functional annotation starts now! 
> Traceback (most recent call last):
>   File "/home/ecastron/programs/eggnog-mapper/emapper.py", line 420, in <module>
>     main(args)
>   File "/home/ecastron/programs/eggnog-mapper/emapper.py", line 246, in main
>     level, nm, desc, cats = annota.get_og_annotations(hitname)
>   File "/home/ecastron/programs/eggnog-mapper/eggnogmapper/annota.py", line 31, in get_og_annotations
>     level, nm, desc, cat = db.fetchone()
> TypeError: 'NoneType' object is not iterable

I don't know if is a bug or I did something wrong.
regards

**Comment by jhcepas** [comment]
looks as a bug. Could you retry with the latest version and let us know?
We are still changing the code and debuging quite actively until releasing version 1.0

**Comment by jhcepas** [comment]
I just tried with the new version and everything seems solved.

**Comment by Sanrrone** [comment]
Dear jhcepas, I tried the server web service of eggnog mapper and when i use a virus protein data set this error appear again, the error (from server) is:

```
#  emapper-0.99.0
# ./emapper.py  --cpu 4 --override -i query_seqs.fa.chunk_001 -d viruses --output allVirSinTOV.faa.chunk_001 --hmm_maxseqlen 5000 -m hmmer --target_orthologs all --tax_scope auto --no_file_comments --go_evidence non-electronic
[32mSequence mapping starts now![0m
[1;34m Processed queries:195 total_time:133.336431026 rate:1.46 q/s[0m
Skipping seed ortholog detection in "viruses" database
[32mFunctional annotation of hits starts now[0m
```

```
26 133.300932169 0.20 q/s
51 133.306641579 0.38 q/s
76 133.311608791 0.57 q/s
101 133.317564487 0.76 q/s
126 133.322782755 0.95 q/s
151 133.326504946 1.13 q/s
176 133.33107686 1.32 q/s
Traceback (most recent call last):
  File "/home/huerta/emapper_production/emapper.py", line 1082, in <module>
    main(args)
  File "/home/huerta/emapper_production/emapper.py", line 237, in main
    annotate_hmm_matches(hmm_hits_file, hmm_hits_file+'.annotations', args)
  File "/home/huerta/emapper_production/emapper.py", line 451, in annotate_hmm_matches
    level, nm, desc, cats = annota.get_og_annotations(hitname)
  File "/home/huerta/emapper_production/eggnogmapper/annota.py", line 34, in get_og_annotations
    level, nm, desc, cat = db.fetchone()
TypeError: 'NoneType' object is not iterable
exitcode: 1
```

the file that I upload is chunked 27 parts but all chunks are with the same error.
maybe a bug?

regards.

**Comment by jhcepas** [comment]
Could you try again? I just updated the online server. 
the program was crashing because some viral OGs have no annotation, therefore missing in the mapper db.

**Comment by Sanrrone** [comment]
Now it's ok, Thanks
