### ISSUE TITLE
how to get COG_number from DIAMOND results?

### ISSUE THREAD

**Issue by jasmineliang** [jhcepas/eggnog-mapper#81]
The eggnog-mapper annotation provides only COG_category, how can I get COG_number based on the DIAMOND results?

**Comment by jhcepas** [comment]
if you are using the latest version of eggnog-mapper, COG numbers are included in the result file ( 10th column, Matching_OGs). 
https://github.com/jhcepas/eggnog-mapper/wiki/Results-Interpretation#project_nameemapperannotations-file

**Comment by jasmineliang** [comment]
What I mean is the COG ID, like COG1132. Is there a way in which I can get COG_ID based on the DIAMOND results? Is the information provided in the og.csv integrated in the eggnog.db?

**Comment by jasmineliang** [comment]
What I mean is the COG ID, like COG1132. Is there a way in which I can get COG_ID based on the DIAMOND results? Is the information provided in the og.csv integrated in the eggnog.db?


Also, I do not understand what the Matching_OGs (10th column) really mean, like  @aproNOG, @bactNOG. Do you have the annotation file for these OGs?


Thanks for your reply!



--

Jie-Liang Liang, Ph D 
Research Associate
School of Life Sciences
Sun Yat-sen University
Tel: +86 20 84111430



At 2018-02-15 19:46:06, "Jaime Huerta-Cepas" <notifications@github.com> wrote:


if you are using the latest version of eggnog-mapper, COG numbers are included in the result file ( 10th column, Matching_OGs).
https://github.com/jhcepas/eggnog-mapper/wiki/Results-Interpretation#project_nameemapperannotations-file
