### ISSUE TITLE
missing COG cat. in eggnog-mapper results

### ISSUE THREAD

**Issue by jumcortez** [jhcepas/eggnog-mapper#84]
Hello, many of my proteins were without classification after run eggnog-mapper. but i can search it manually and get the category. why eggnog-mapper could not found the category from this proteins?

**Comment by jhcepas** [comment]
hi, most probably, because the orthology filtering in eggnog-mapper considered those hits as less reliable (or at least not supported by orthology prediction), therefore no annotations are transferred to the query sequence.

**Comment by jumcortez** [comment]
hello, thanks for the answer. Eggnog-mapper uses a different db? because when i search it manually i can get the category.

**Comment by jhcepas** [comment]
it is the same database, but if the query sequence does not get a fine grained ortholog assignment within the matching eggNOG group, it does not produce an annotation line in eggNOG-mapper.

**Comment by jumcortez** [comment]
using hmm instead diamond i could get all categories.

**Comment by jhcepas** [comment]
I see, it looks that it may then be a distant homology case. Or at least not a straightforward annotation.
