### ISSUE TITLE
Proper method for DIAMOND large scale analysis on a cluster?

### ISSUE THREAD

**Issue by nigiord** [jhcepas/eggnog-mapper#85]
The [documentation](https://github.com/jhcepas/eggnog-mapper/wiki/Setting-up-large-scale-analyses) recommends to put `data/eggnog.db` in the fastest disk available when making large scale analysis, recommending `/dev/shm` which is a memory based filesystem. This is however quite inconvenient when running an annotation pipeline on a cluster, because nodes do not share memory, so jobs running on different nodes will not have access to the same `/dev/shm`.

What could be the best way to do large scale analysis on this kind of setup?

My first attempt was to add a step in my GNU Make pipeline that loads the eggnog.db file into `/dev/shm` before running eggnog-mapper, checking that the file does not exist and waiting for it to have the correct size (in case it is currently copied by another job).

```
$(ANNOTDIR)/%.emapper.annotations: $(ANNOTDIR)/%.emapper.seed_orthologs
	@if [ ! -f $(RAMDATA)/eggnog.db ]; \
		then echo "[$(HOSTNAME), $*] Copying eggnog.db in $(RAMDATA)"; \
		mkdir -p $(RAMDATA); \
		cp -n $(EMAPDATA)/eggnog.db $(RAMDATA)/eggnog.db; \
		echo "[$(HOSTNAME), $*] data/eggnog.db copied in $(RAMDATA)"; \
	fi; \
	while [ $(shell stat -c%s "$(EMAPDATA)/eggnog.db") \
			!= $(shell stat -c%s "$(RAMDATA)/eggnog.db") ]; \
		do echo "[$(HOSTNAME), $*] Waiting for DB..."; \
		sleep 30; \
	done; \
	python2 $(EMAPRUN) \
		--annotate_hits_table $(realpath $<) \
		--output_dir $(ANNOTDIR) \
		--output $* \
		--data_dir $(RAMDATA) \
		--cpu 1 \
		--override
```

It ~kinda works (I have strange I/O errors sometimes), but the main problem I have is that eggnog.db stays forever in `/dev/shm` on each node of the cluster, and it takes a long time to manually free this memory afterwards (because I have to manually connect to each node of the cluster, and delete `/dev/shm/data/eggnog.db` myself).

Ideally, I would like something that works like --servermode ([doc](https://github.com/jhcepas/eggnog-mapper/wiki/Advanced-usage-and-tips)) but compatible with the diamond 2-step pipeline described [here](https://github.com/jhcepas/eggnog-mapper/wiki/Setting-up-large-scale-analyses). So is there a way to load eggnog.db in memory for diamond-based annotation, analogous to what is possible for HMMER databases?

**Comment by jhcepas** [comment]
I don't know any way to run diamond in server mode. We usually follow similar strategies as you: copying DBs to each node, then delete them. If /dev/shm gives you problems, copying to a local disk in each node would also work well.
