### ISSUE TITLE
No results reported for many sequences

### ISSUE THREAD

**Issue by styler44** [jhcepas/eggnog-mapper#88]
Some sequences are not receiving COG cats. which I assume has to do with low quality matches.  However, I just noticed that not all of the sequences are showing in the report.  In one case over 400 sequences were submitted but there are results for only 40 or 50.

**Comment by jhcepas** [comment]
sequences without functional annotation (i.e. no annotated orthologs detected) are not reported. If you have any clear case that should have been annotated but it was not, let me know and I can check that particular case
