### ISSUE TITLE
running time and memory

### ISSUE THREAD

**Issue by chloelulu** [jhcepas/eggnog-mapper#89]
Hi, 
I am using diamond mode running my contigs, which has 1.2 Gb. I have run it for 24 hours. Still no response, but I know it is still running background. 
The code I used is '`emapper.py -i MEGAHIT_D.contigs.fa --output p53_maNOG  -m diamond --cpu 16`'
It seems that it has consumed 294% of my CPUs. And my storage has been consumed a lot, but no output. 
I check the running procedure, as shown below.
`ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10`
`%CPU   PID     COMMAND`
`293 45684  /home/eggnog-mapper/eggnog-mapper/bin/diamond blastp -d /home/eggnog-mapper/eggnog-mapper/data/eggnog_proteins.dmnd -q /home/co_assembly/assemblers_D_megahit/MEGAHIT_D.contigs.fa --more-sensitive --threads 16 -e 0.001000 -o /home/co_assembly/assemblers_D_megahit/eggNOG/emappertmp_dmdn_3zPB8G/22d2eccfbe584186a99198bd1cc4fa51 --top 3`
Is there anything wrong? 
Thanks a lot.

**Comment by jhcepas** [comment]
as far as the diamond process with using CPU time, I would it is normal. DIAMOND writes hidden temp files, so it is ok if you don't see any output yet.
