### ISSUE TITLE
waiting too much?

### ISSUE THREAD

**Issue by microalgues** [jhcepas/eggnog-mapper#90]
Hi everybody,
I have run eggNOG-mapper for almost one week in my local computer. I have installed eggNOG in my SSD and the euk database in the HDD, so I created a symbolic link to the euk database call /data.
Is this normal to wait so much? My query is less than half million proteins of unicellular eukaryote.
The code is bellow:
```
python emapper.py -i /media/javier/Datas/Transcriptomics/DATA/FINAL.aa_pub.fa --output /media/javier/Datas/Transcriptomics/DATA/FINAL_eggNOG -d euk --cpu 16
#  emapper-1.0.3
# ./emapper.py  -i /media/javier/Datas/Transcriptomics/DATA/FINAL.aa_pub.fa --output /media/javier/Datas/Transcriptomics/DATA/FINAL_eggNOG -d euk --cpu 16
/home/javier/Software/eggnog-mapper-1.0.3/data/hmmdb_levels/euk_500/euk_500.hmm
Sequence mapping starts now!

```
Thank you so much

**Comment by jhcepas** [comment]
You process is not going to finish soon. For large datasets you need to use diamond mode. The annotation rate for the euk HMM database is about 4 queries/second using 10 CPUs depending on hardware, so make the numbers and you will see that you need a very large paralelization to annotate 0.5M proteins :)
Diamond mode works as good as the HMM mode in our tests, and you can always re-run the non-annotated diamond queries using HMM mode.
