### ISSUE TITLE
no "[R] General function prediction only" in COG_category

### ISSUE THREAD

**Issue by jasmineliang** [jhcepas/eggnog-mapper#93]
hi~
My eggnog-mapper results showed that there are only 24 COG categories. Then I checked the all_OG_annotations.tsv file and found that there are only 24 COG categories, with "[R] General function prediction only" missing. Why eggNOG database did not consider this category?

**Comment by jhcepas** [comment]
the eggnog annotation pipeline does not use the [R] COG category for classifying groups because it is too generic. We either classify as Unknown or we assign a more specific category.
