### ISSUE TITLE
hmmpgmd error ?

### ISSUE THREAD

**Issue by hyyuu** [jhcepas/eggnog-mapper#95]
Hello.
Thank you very much for this useful software. 

I tried to execute the HMM mode to identify ortholog using --usemem option.

But it seems to stop in the middle with this error.
ValueError: hmmpgmd error: @--hmmdb 1

And here are the last few lines of the log. 

```
File "/home/share/tools/eggnog-mapper/eggnogmapper/search.py", line 127, in scan_hits
    raise ValueError('hmmpgmd error: %s' % data[:50])
ValueError: hmmpgmd error: @--hmmdb 1
>Ampp@c0_g1_i1::g.4601
```
 
Could you please tell me where I have done wrong ? 

I am sorry if it is a simple question. Thank you very much for your help. :)

**Comment by jhcepas** [comment]
hard to say without having a test case, but it looks like a format problem with some of your query sequences (weird characters in name or seq?)
