### ISSUE TITLE
Running batch eggnog jobs leads to database error

### ISSUE THREAD

**Issue by jpiechura** [jhcepas/eggnog-mapper#98]
We are running emapper.py  in diamond mode on multiple genomes at once on aws cloud, with all samples sharing the same eggnog.db file in a shared location. For some samples, we are receiving errors from sqlite3 saying :sqlite3.OperationalError: database is locked. This error can occur at several different steps. The result is that eggnog terminates prematurely. Here are some example errors:

Command:
emapper.py -i proteins.fa --output sample -m diamond --cpu 32

Error 1:
Traceback (most recent call last):
  File "/eggnog/emapper.py", line 1001, in <module>
    main(args)
  File "/eggnog/emapper.py", line 261, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/eggnog/emapper.py", line 712, in annotate_hits_file
    og_cat, og_desc = annota.get_best_og_description(match_nogs)
  File "/eggnog/eggnogmapper/annota.py", line 45, in get_best_og_description
    if db.execute(cmd):
sqlite3.OperationalError: database is locked

Error 2:
Traceback (most recent call last):
  File "/eggnog/emapper.py", line 1001, in <module>
    main(args)
  File "/eggnog/emapper.py", line 261, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/eggnog/emapper.py", line 693, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/home/ubuntu/anaconda3/envs/funannotate_env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
sqlite3.OperationalError: database is locked

Any way to get around this issue so that we can use eggnog on multiple samples at once without samples randomly failing prematurely due to database issues?

**Comment by jhcepas** [comment]
is the database stored in a shared filesystem (NFS, etc)? this is not supported by sqlite. In general the data/ directory should live a in a local disk if possible. Or at least the sqlite file. 
See this for some recommendations: https://github.com/jhcepas/eggnog-mapper/wiki/Advanced-usage-and-tips

**Comment by jpiechura** [comment]
Unfortunately we are not able to store the data directory in a local disk due to our cloud setup, and the server mode will not help us in this case. could you possible recommend a different fix? is there a package other than sqlite that we could substitute that would allow multiple runs to access the same database without being locked out of the eggnog.db? 

Further, we are a bit confused as to why the eggnog.db file is getting locked in the first place, because as far as we understand, such databases should only be locked if a file is trying to write the database, but emapper.py only seems to be reading this database. if you have any insights for why eggnog.db is being locked, it would be a big help. Thanks!

**Comment by jhcepas** [comment]
we use several strategies: 1) submit a job that, before computing, copies eggnog.db to the local /dev/shm and symlink from data/ or use custom data dire (see command line documentation). shm is a memory map and provides also the best performance; 2) use the same method but with /tmp (usually a local disk); 3 ) run eggnog-mapper in two phases . First run the mapping (which does not require access to the database), collect results, and run annotation in a separate server where you have access to a local disk. See these recommendations: https://github.com/jhcepas/eggnog-mapper/wiki/Setting-up-large-scale-analyses; or 4) talk to your system administrators and ask for local installation of eggnog-mapper. 

I have used emapper in a bunch on cluster systems, including cloud solutions, and so far I always found at least one of the above strategies to work.     

Regarding potential changes in eggnog-mapper: sqlite under NFS is officially unreliable, even for concurrent reading. I could not find any way to make it work or a decent alternative. A more extreme solution would be to dump the sqlite db into a mysql server, and modify eggnog-mapper api to query that server. But that would make emapper much more difficult to port, etc.
